/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.2
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateSkillDto,
  SkillsControllerCreate200,
  SkillsControllerFindAll200,
  SkillsControllerFindAllParams,
  SkillsControllerRemove200,
  SkillsControllerUpdate200,
  UpdateSkillDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * categoryId 를 넘기면 해당 카테고리의 skill 만, jobTypeId 를 넘기면 해당 직군에 매핑된 skill 만,
 * search 를 넘기면 name 부분 일치로 필터링합니다. (생략 시 전체, 여러 개를 함께 넘기면 AND)
 *
 * sort 는 id·name 만 허용하며 기본값은 name 입니다.
 * @summary skill 목록 조회
 */
export const skillsControllerFindAll = (
  params: SkillsControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SkillsControllerFindAll200>(
    { url: `/skills`, method: "GET", params, signal },
    options,
  );
};

export const getSkillsControllerFindAllQueryKey = (
  params?: SkillsControllerFindAllParams,
) => {
  return [`/skills`, ...(params ? [params] : [])] as const;
};

export const getSkillsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof skillsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: SkillsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSkillsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof skillsControllerFindAll>>
  > = ({ signal }) => skillsControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof skillsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SkillsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof skillsControllerFindAll>>
>;
export type SkillsControllerFindAllQueryError = ErrorType<unknown>;

export function useSkillsControllerFindAll<
  TData = Awaited<ReturnType<typeof skillsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: SkillsControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof skillsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof skillsControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSkillsControllerFindAll<
  TData = Awaited<ReturnType<typeof skillsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: SkillsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof skillsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof skillsControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSkillsControllerFindAll<
  TData = Awaited<ReturnType<typeof skillsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: SkillsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary skill 목록 조회
 */

export function useSkillsControllerFindAll<
  TData = Awaited<ReturnType<typeof skillsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: SkillsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSkillsControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * jobTypeIds 로 이 스킬이 속한 직군을 함께 지정합니다. 빈 배열은 허용하지 않으며,
 * 전 직군 공통 스킬이면 모든 직군 ID 를 넣습니다.
 * @summary skill 생성 (ADMIN)
 */
export const skillsControllerCreate = (
  createSkillDto: BodyType<CreateSkillDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SkillsControllerCreate200>(
    {
      url: `/skills`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createSkillDto,
      signal,
    },
    options,
  );
};

export const getSkillsControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof skillsControllerCreate>>,
    TError,
    { data: BodyType<CreateSkillDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof skillsControllerCreate>>,
  TError,
  { data: BodyType<CreateSkillDto> },
  TContext
> => {
  const mutationKey = ["skillsControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof skillsControllerCreate>>,
    { data: BodyType<CreateSkillDto> }
  > = (props) => {
    const { data } = props ?? {};

    return skillsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SkillsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof skillsControllerCreate>>
>;
export type SkillsControllerCreateMutationBody = BodyType<CreateSkillDto>;
export type SkillsControllerCreateMutationError = ErrorType<void>;

/**
 * @summary skill 생성 (ADMIN)
 */
export const useSkillsControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof skillsControllerCreate>>,
      TError,
      { data: BodyType<CreateSkillDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof skillsControllerCreate>>,
  TError,
  { data: BodyType<CreateSkillDto> },
  TContext
> => {
  return useMutation(
    getSkillsControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * 넘긴 필드만 수정합니다. jobTypeIds 를 넘기면 직군 매핑을 그 목록으로 통째로 교체하고,
 * 생략하면 기존 매핑을 그대로 둡니다.
 * @summary skill 수정 (ADMIN)
 */
export const skillsControllerUpdate = (
  id: number,
  updateSkillDto: BodyType<UpdateSkillDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SkillsControllerUpdate200>(
    {
      url: `/skills/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateSkillDto,
      signal,
    },
    options,
  );
};

export const getSkillsControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof skillsControllerUpdate>>,
    TError,
    { id: number; data: BodyType<UpdateSkillDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof skillsControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateSkillDto> },
  TContext
> => {
  const mutationKey = ["skillsControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof skillsControllerUpdate>>,
    { id: number; data: BodyType<UpdateSkillDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return skillsControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SkillsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof skillsControllerUpdate>>
>;
export type SkillsControllerUpdateMutationBody = BodyType<UpdateSkillDto>;
export type SkillsControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary skill 수정 (ADMIN)
 */
export const useSkillsControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof skillsControllerUpdate>>,
      TError,
      { id: number; data: BodyType<UpdateSkillDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof skillsControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateSkillDto> },
  TContext
> => {
  return useMutation(
    getSkillsControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary skill 삭제 (ADMIN)
 */
export const skillsControllerRemove = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SkillsControllerRemove200>(
    { url: `/skills/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getSkillsControllerRemoveMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof skillsControllerRemove>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof skillsControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["skillsControllerRemove"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof skillsControllerRemove>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return skillsControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SkillsControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof skillsControllerRemove>>
>;

export type SkillsControllerRemoveMutationError = ErrorType<void>;

/**
 * @summary skill 삭제 (ADMIN)
 */
export const useSkillsControllerRemove = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof skillsControllerRemove>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof skillsControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getSkillsControllerRemoveMutationOptions(options),
    queryClient,
  );
};
