/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ConnectionRequestsControllerAcceptRequest200,
  ConnectionRequestsControllerCancelRequest200,
  ConnectionRequestsControllerCreateRequest200,
  ConnectionRequestsControllerGetReceived200,
  ConnectionRequestsControllerGetReceivedParams,
  ConnectionRequestsControllerGetSent200,
  ConnectionRequestsControllerGetSentParams,
  ConnectionRequestsControllerRejectRequest200,
  CreateConnectionRequestDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 내 카드(requesterCardId)로 상대 카드(receiverCardId)에 연결을 요청합니다.
 *
 * **요청 body**
 * - requesterCardId: 요청자의 카드 ID
 * - receiverCardId: 요청 대상자의 카드 ID
 * - message: 첨부할 메세지 (optional)
 *
 * **응답 body**
 * - id: 연결 요청 ID
 * - status: 요청 상태 (0 대기 / 1 수락 / 2 거절 / 3 취소)
 * - message: 첨부한 메세지
 * - card: 요청을 받은 상대 카드
 * - createdAt: 요청 생성 시각
 * @summary 연결 요청 보내기
 */
export const connectionRequestsControllerCreateRequest = (
  createConnectionRequestDto: BodyType<CreateConnectionRequestDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionRequestsControllerCreateRequest200>(
    {
      url: `/connection-requests`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createConnectionRequestDto,
      signal,
    },
    options,
  );
};

export const getConnectionRequestsControllerCreateRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof connectionRequestsControllerCreateRequest>>,
    TError,
    { data: BodyType<CreateConnectionRequestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof connectionRequestsControllerCreateRequest>>,
  TError,
  { data: BodyType<CreateConnectionRequestDto> },
  TContext
> => {
  const mutationKey = ["connectionRequestsControllerCreateRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof connectionRequestsControllerCreateRequest>>,
    { data: BodyType<CreateConnectionRequestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return connectionRequestsControllerCreateRequest(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConnectionRequestsControllerCreateRequestMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof connectionRequestsControllerCreateRequest>>
  >;
export type ConnectionRequestsControllerCreateRequestMutationBody =
  BodyType<CreateConnectionRequestDto>;
export type ConnectionRequestsControllerCreateRequestMutationError =
  ErrorType<void>;

/**
 * @summary 연결 요청 보내기
 */
export const useConnectionRequestsControllerCreateRequest = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof connectionRequestsControllerCreateRequest>>,
      TError,
      { data: BodyType<CreateConnectionRequestDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof connectionRequestsControllerCreateRequest>>,
  TError,
  { data: BodyType<CreateConnectionRequestDto> },
  TContext
> => {
  return useMutation(
    getConnectionRequestsControllerCreateRequestMutationOptions(options),
    queryClient,
  );
};
/**
 * 내 카드(cardId)가 받은 대기(PENDING) 상태 요청 목록을 페이지네이션으로 조회합니다.
 *
 * **요청 query**
 * - cardId: 조회 기준이 되는 내 카드 ID
 * - page, limit, sort, order: 페이지네이션 옵션
 *
 * **응답 body**
 * - items: 연결 요청 목록 (각 항목의 card 는 요청을 보낸 상대 카드)
 * - metadata: 페이지네이션 정보
 * @summary 받은 연결 요청함 조회
 */
export const connectionRequestsControllerGetReceived = (
  params: ConnectionRequestsControllerGetReceivedParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionRequestsControllerGetReceived200>(
    { url: `/connection-requests/received`, method: "GET", params, signal },
    options,
  );
};

export const getConnectionRequestsControllerGetReceivedQueryKey = (
  params?: ConnectionRequestsControllerGetReceivedParams,
) => {
  return [
    `/connection-requests/received`,
    ...(params ? [params] : []),
  ] as const;
};

export const getConnectionRequestsControllerGetReceivedQueryOptions = <
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetReceivedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getConnectionRequestsControllerGetReceivedQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>
  > = ({ signal }) =>
    connectionRequestsControllerGetReceived(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ConnectionRequestsControllerGetReceivedQueryResult = NonNullable<
  Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>
>;
export type ConnectionRequestsControllerGetReceivedQueryError = ErrorType<void>;

export function useConnectionRequestsControllerGetReceived<
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetReceivedParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
          TError,
          Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useConnectionRequestsControllerGetReceived<
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetReceivedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
          TError,
          Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useConnectionRequestsControllerGetReceived<
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetReceivedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 받은 연결 요청함 조회
 */

export function useConnectionRequestsControllerGetReceived<
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetReceivedParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetReceived>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getConnectionRequestsControllerGetReceivedQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 내 카드(cardId)가 보낸 요청 목록을 상태 무관으로 페이지네이션 조회합니다.
 *
 * **요청 query**
 * - cardId: 조회 기준이 되는 내 카드 ID
 * - page, limit, sort, order: 페이지네이션 옵션
 *
 * **응답 body**
 * - items: 연결 요청 목록 (각 항목의 card 는 요청을 받은 상대 카드)
 * - metadata: 페이지네이션 정보
 * @summary 보낸 연결 요청함 조회
 */
export const connectionRequestsControllerGetSent = (
  params: ConnectionRequestsControllerGetSentParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionRequestsControllerGetSent200>(
    { url: `/connection-requests/sent`, method: "GET", params, signal },
    options,
  );
};

export const getConnectionRequestsControllerGetSentQueryKey = (
  params?: ConnectionRequestsControllerGetSentParams,
) => {
  return [`/connection-requests/sent`, ...(params ? [params] : [])] as const;
};

export const getConnectionRequestsControllerGetSentQueryOptions = <
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetSentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getConnectionRequestsControllerGetSentQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>
  > = ({ signal }) =>
    connectionRequestsControllerGetSent(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ConnectionRequestsControllerGetSentQueryResult = NonNullable<
  Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>
>;
export type ConnectionRequestsControllerGetSentQueryError = ErrorType<void>;

export function useConnectionRequestsControllerGetSent<
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetSentParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
          TError,
          Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useConnectionRequestsControllerGetSent<
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetSentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
          TError,
          Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useConnectionRequestsControllerGetSent<
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetSentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 보낸 연결 요청함 조회
 */

export function useConnectionRequestsControllerGetSent<
  TData = Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
  TError = ErrorType<void>,
>(
  params: ConnectionRequestsControllerGetSentParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionRequestsControllerGetSent>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getConnectionRequestsControllerGetSentQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 받은 요청을 수락하면 양쪽 카드의 스냅샷을 떠 보관(연결)이 생성됩니다.
 *
 * **path param**
 * - id: 연결 요청 ID
 *
 * **응답 body**
 * - 없음
 * @summary 연결 요청 수락
 */
export const connectionRequestsControllerAcceptRequest = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionRequestsControllerAcceptRequest200>(
    { url: `/connection-requests/${id}/accept`, method: "PATCH", signal },
    options,
  );
};

export const getConnectionRequestsControllerAcceptRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof connectionRequestsControllerAcceptRequest>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof connectionRequestsControllerAcceptRequest>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["connectionRequestsControllerAcceptRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof connectionRequestsControllerAcceptRequest>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return connectionRequestsControllerAcceptRequest(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConnectionRequestsControllerAcceptRequestMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof connectionRequestsControllerAcceptRequest>>
  >;

export type ConnectionRequestsControllerAcceptRequestMutationError =
  ErrorType<void>;

/**
 * @summary 연결 요청 수락
 */
export const useConnectionRequestsControllerAcceptRequest = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof connectionRequestsControllerAcceptRequest>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof connectionRequestsControllerAcceptRequest>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getConnectionRequestsControllerAcceptRequestMutationOptions(options),
    queryClient,
  );
};
/**
 * 받은 요청을 거절합니다.
 *
 * **path param**
 * - id: 연결 요청 ID
 *
 * **응답 body**
 * - 없음
 * @summary 연결 요청 거절
 */
export const connectionRequestsControllerRejectRequest = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionRequestsControllerRejectRequest200>(
    { url: `/connection-requests/${id}/reject`, method: "PATCH", signal },
    options,
  );
};

export const getConnectionRequestsControllerRejectRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof connectionRequestsControllerRejectRequest>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof connectionRequestsControllerRejectRequest>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["connectionRequestsControllerRejectRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof connectionRequestsControllerRejectRequest>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return connectionRequestsControllerRejectRequest(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConnectionRequestsControllerRejectRequestMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof connectionRequestsControllerRejectRequest>>
  >;

export type ConnectionRequestsControllerRejectRequestMutationError =
  ErrorType<void>;

/**
 * @summary 연결 요청 거절
 */
export const useConnectionRequestsControllerRejectRequest = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof connectionRequestsControllerRejectRequest>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof connectionRequestsControllerRejectRequest>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getConnectionRequestsControllerRejectRequestMutationOptions(options),
    queryClient,
  );
};
/**
 * 내가 보낸 요청을 취소합니다.
 *
 * **path param**
 * - id: 연결 요청 ID
 *
 * **응답 body**
 * - 없음
 * @summary 연결 요청 취소
 */
export const connectionRequestsControllerCancelRequest = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionRequestsControllerCancelRequest200>(
    { url: `/connection-requests/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getConnectionRequestsControllerCancelRequestMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof connectionRequestsControllerCancelRequest>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof connectionRequestsControllerCancelRequest>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["connectionRequestsControllerCancelRequest"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof connectionRequestsControllerCancelRequest>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return connectionRequestsControllerCancelRequest(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConnectionRequestsControllerCancelRequestMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof connectionRequestsControllerCancelRequest>>
  >;

export type ConnectionRequestsControllerCancelRequestMutationError =
  ErrorType<void>;

/**
 * @summary 연결 요청 취소
 */
export const useConnectionRequestsControllerCancelRequest = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof connectionRequestsControllerCancelRequest>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof connectionRequestsControllerCancelRequest>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getConnectionRequestsControllerCancelRequestMutationOptions(options),
    queryClient,
  );
};
