/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  FilesControllerUploadCardBackgroundImage200,
  FilesControllerUploadPersonalityImage200,
  FilesControllerUploadProfileImage200,
  UploadImageDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 이미지 1장(png/jpg/webp, 최대 5MB)을 `multipart/form-data` 의 `file` 필드로 받는다.
 *
 * 업로드 시 아래 4개 객체가 `profile/{YYYY}/{mm}/{uuid}/` 하위에 저장된다.
 * - `origin.webp` : 원본(리사이즈 없이 webp 변환만)
 * - `72.webp` / `56.webp` / `48.webp` : 정사각 cover 크롭 파생본
 *
 * 응답 `url` 은 uuid 까지의 base URL 이며, 실제 이미지는 뒤에 파일명을 붙여 접근한다.
 * 예) `${url}/origin.webp`, `${url}/72.webp`
 * @summary 프로필 이미지 업로드
 */
export const filesControllerUploadProfileImage = (
  uploadImageDto: BodyType<UploadImageDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, uploadImageDto.file);

  return customInstance<FilesControllerUploadProfileImage200>(
    {
      url: `/files/profile-image/upload`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getFilesControllerUploadProfileImageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesControllerUploadProfileImage>>,
    TError,
    { data: BodyType<UploadImageDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesControllerUploadProfileImage>>,
  TError,
  { data: BodyType<UploadImageDto> },
  TContext
> => {
  const mutationKey = ["filesControllerUploadProfileImage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerUploadProfileImage>>,
    { data: BodyType<UploadImageDto> }
  > = (props) => {
    const { data } = props ?? {};

    return filesControllerUploadProfileImage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilesControllerUploadProfileImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerUploadProfileImage>>
>;
export type FilesControllerUploadProfileImageMutationBody =
  BodyType<UploadImageDto>;
export type FilesControllerUploadProfileImageMutationError = ErrorType<void>;

/**
 * @summary 프로필 이미지 업로드
 */
export const useFilesControllerUploadProfileImage = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesControllerUploadProfileImage>>,
      TError,
      { data: BodyType<UploadImageDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filesControllerUploadProfileImage>>,
  TError,
  { data: BodyType<UploadImageDto> },
  TContext
> => {
  return useMutation(
    getFilesControllerUploadProfileImageMutationOptions(options),
    queryClient,
  );
};
/**
 * 이미지 1장(png/jpg/webp, 최대 5MB)을 `multipart/form-data` 의 `file` 필드로 받는다.
 *
 * 업로드 시 아래 2개 객체가 `personality/{YYYY}/{mm}/{uuid}/` 하위에 저장된다.
 * - `origin.webp` : 원본(리사이즈 없이 webp 변환만)
 * - `36.webp` : 36x36 정사각 cover 크롭 파생본
 *
 * 응답 `url` 은 uuid 까지의 base URL 이며, 실제 이미지는 뒤에 파일명을 붙여 접근한다.
 * 예) `${url}/origin.webp`, `${url}/36.webp`
 * @summary 개성(personality) 이미지 업로드 (ADMIN)
 */
export const filesControllerUploadPersonalityImage = (
  uploadImageDto: BodyType<UploadImageDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, uploadImageDto.file);

  return customInstance<FilesControllerUploadPersonalityImage200>(
    {
      url: `/files/personality-image/upload`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getFilesControllerUploadPersonalityImageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesControllerUploadPersonalityImage>>,
    TError,
    { data: BodyType<UploadImageDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesControllerUploadPersonalityImage>>,
  TError,
  { data: BodyType<UploadImageDto> },
  TContext
> => {
  const mutationKey = ["filesControllerUploadPersonalityImage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerUploadPersonalityImage>>,
    { data: BodyType<UploadImageDto> }
  > = (props) => {
    const { data } = props ?? {};

    return filesControllerUploadPersonalityImage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilesControllerUploadPersonalityImageMutationResult = NonNullable<
  Awaited<ReturnType<typeof filesControllerUploadPersonalityImage>>
>;
export type FilesControllerUploadPersonalityImageMutationBody =
  BodyType<UploadImageDto>;
export type FilesControllerUploadPersonalityImageMutationError =
  ErrorType<void>;

/**
 * @summary 개성(personality) 이미지 업로드 (ADMIN)
 */
export const useFilesControllerUploadPersonalityImage = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesControllerUploadPersonalityImage>>,
      TError,
      { data: BodyType<UploadImageDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filesControllerUploadPersonalityImage>>,
  TError,
  { data: BodyType<UploadImageDto> },
  TContext
> => {
  return useMutation(
    getFilesControllerUploadPersonalityImageMutationOptions(options),
    queryClient,
  );
};
/**
 * 이미지 1장(png/jpg/webp, 최대 5MB)을 `multipart/form-data` 의 `file` 필드로 받는다.
 *
 * 업로드 시 아래 2개 객체가 `card-background/{YYYY}/{mm}/{uuid}/` 하위에 저장된다.
 * - `origin.webp` : 원본(리사이즈 없이 webp 변환만)
 * - `282x400.webp` : 282x400 cover 크롭 파생본(카드 표시용)
 *
 * 응답 `url` 은 uuid 까지의 base URL 이며, 실제 이미지는 뒤에 파일명을 붙여 접근한다.
 * 예) `${url}/origin.webp`, `${url}/282x400.webp`
 * @summary 카드 배경 이미지 업로드 (ADMIN)
 */
export const filesControllerUploadCardBackgroundImage = (
  uploadImageDto: BodyType<UploadImageDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  const formData = new FormData();
  formData.append(`file`, uploadImageDto.file);

  return customInstance<FilesControllerUploadCardBackgroundImage200>(
    {
      url: `/files/card-background-image/upload`,
      method: "POST",
      headers: { "Content-Type": "multipart/form-data" },
      data: formData,
      signal,
    },
    options,
  );
};

export const getFilesControllerUploadCardBackgroundImageMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof filesControllerUploadCardBackgroundImage>>,
    TError,
    { data: BodyType<UploadImageDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof filesControllerUploadCardBackgroundImage>>,
  TError,
  { data: BodyType<UploadImageDto> },
  TContext
> => {
  const mutationKey = ["filesControllerUploadCardBackgroundImage"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof filesControllerUploadCardBackgroundImage>>,
    { data: BodyType<UploadImageDto> }
  > = (props) => {
    const { data } = props ?? {};

    return filesControllerUploadCardBackgroundImage(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type FilesControllerUploadCardBackgroundImageMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof filesControllerUploadCardBackgroundImage>>
  >;
export type FilesControllerUploadCardBackgroundImageMutationBody =
  BodyType<UploadImageDto>;
export type FilesControllerUploadCardBackgroundImageMutationError =
  ErrorType<void>;

/**
 * @summary 카드 배경 이미지 업로드 (ADMIN)
 */
export const useFilesControllerUploadCardBackgroundImage = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof filesControllerUploadCardBackgroundImage>>,
      TError,
      { data: BodyType<UploadImageDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof filesControllerUploadCardBackgroundImage>>,
  TError,
  { data: BodyType<UploadImageDto> },
  TContext
> => {
  return useMutation(
    getFilesControllerUploadCardBackgroundImageMutationOptions(options),
    queryClient,
  );
};
