/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateProfileCardDto,
  ProfileCardsControllerCreateProfileCard200,
  ProfileCardsControllerDeleteProfileCard200,
  ProfileCardsControllerGetProfileCard200,
  ProfileCardsControllerGetProfileCards200,
  ProfileCardsControllerGetProfileCardsParams,
  ProfileCardsControllerUpdateProfileCard200,
  UpdateProfileCardDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 로그인한 유저 본인이 소유한 프로필 카드 목록을 페이지네이션으로 조회합니다.
 *
 * ★ experiences 는 **대표 경험 1개만**(sortOrder 가장 앞) 포함됩니다.
 *   전체 경험이 필요하면 단건 조회(`GET /profile-cards/{id}`)를 사용하세요.
 *   그 외 응답 필드(skills·links·personality 등)는 단건 조회와 동일합니다.
 * @summary 유저 프로필 카드 목록 조회
 */
export const profileCardsControllerGetProfileCards = (
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardsControllerGetProfileCards200>(
    { url: `/profile-cards`, method: "GET", params, signal },
    options,
  );
};

export const getProfileCardsControllerGetProfileCardsQueryKey = (
  params?: ProfileCardsControllerGetProfileCardsParams,
) => {
  return [`/profile-cards`, ...(params ? [params] : [])] as const;
};

export const getProfileCardsControllerGetProfileCardsQueryOptions = <
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProfileCardsControllerGetProfileCardsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>
  > = ({ signal }) =>
    profileCardsControllerGetProfileCards(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileCardsControllerGetProfileCardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>
>;
export type ProfileCardsControllerGetProfileCardsQueryError = ErrorType<void>;

export function useProfileCardsControllerGetProfileCards<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
          TError,
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardsControllerGetProfileCards<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
          TError,
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardsControllerGetProfileCards<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 유저 프로필 카드 목록 조회
 */

export function useProfileCardsControllerGetProfileCards<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfileCardsControllerGetProfileCardsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 유저 프로필 카드를 생성합니다. 동작 방식은 두 가지로 나뉩니다.
 *
 * 1. 유저의 Default 프로필 카드가 없는 경우 (온보딩)
 *    → 이 카드가 Default 카드로 생성되며, purposeId 는 요청값과 무관하게 null 로 고정됩니다.
 * 2. 유저의 Default 프로필 카드가 있는 경우 (추후 카드 생성 시점)
 *    → jobTypeId / purposeId 는 요청값으로 설정되고, Default 카드에서는 nickname 과 links 만 기본값으로 복사됩니다.
 *    → 나머지 필드는 비워둔 채 생성되며 이후 update 로 채웁니다.
 *
 * ★ 응답은 관계까지 포함한 완전한 카드(단건 조회와 동일 형태)입니다.
 *   experiences 는 전체 포함이며, 첫 카드(온보딩)는 아직 비어 있어 `[]` 로 나옵니다.
 * @summary 유저 프로필 카드 생성
 */
export const profileCardsControllerCreateProfileCard = (
  createProfileCardDto: BodyType<CreateProfileCardDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardsControllerCreateProfileCard200>(
    {
      url: `/profile-cards`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createProfileCardDto,
      signal,
    },
    options,
  );
};

export const getProfileCardsControllerCreateProfileCardMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
    TError,
    { data: BodyType<CreateProfileCardDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
  TError,
  { data: BodyType<CreateProfileCardDto> },
  TContext
> => {
  const mutationKey = ["profileCardsControllerCreateProfileCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
    { data: BodyType<CreateProfileCardDto> }
  > = (props) => {
    const { data } = props ?? {};

    return profileCardsControllerCreateProfileCard(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCardsControllerCreateProfileCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>
>;
export type ProfileCardsControllerCreateProfileCardMutationBody =
  BodyType<CreateProfileCardDto>;
export type ProfileCardsControllerCreateProfileCardMutationError =
  ErrorType<void>;

/**
 * @summary 유저 프로필 카드 생성
 */
export const useProfileCardsControllerCreateProfileCard = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
      TError,
      { data: BodyType<CreateProfileCardDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
  TError,
  { data: BodyType<CreateProfileCardDto> },
  TContext
> => {
  return useMutation(
    getProfileCardsControllerCreateProfileCardMutationOptions(options),
    queryClient,
  );
};
/**
 * 로그인한 유저 본인이 소유한 프로필 카드를 id 로 조회합니다.
 * 본인 소유가 아니거나 존재하지 않으면 404 를 반환합니다.
 *
 * ★ experiences 는 **전체**를 sortOrder 오름차순으로 포함합니다.
 *   (목록 조회는 대표 1개만 — 차이 주의)
 * @summary 유저 프로필 카드 단건 조회
 */
export const profileCardsControllerGetProfileCard = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardsControllerGetProfileCard200>(
    { url: `/profile-cards/${id}`, method: "GET", signal },
    options,
  );
};

export const getProfileCardsControllerGetProfileCardQueryKey = (id: string) => {
  return [`/profile-cards/${id}`] as const;
};

export const getProfileCardsControllerGetProfileCardQueryOptions = <
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProfileCardsControllerGetProfileCardQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>
  > = ({ signal }) =>
    profileCardsControllerGetProfileCard(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileCardsControllerGetProfileCardQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>
>;
export type ProfileCardsControllerGetProfileCardQueryError = ErrorType<void>;

export function useProfileCardsControllerGetProfileCard<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
          TError,
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardsControllerGetProfileCard<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
          TError,
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardsControllerGetProfileCard<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 유저 프로필 카드 단건 조회
 */

export function useProfileCardsControllerGetProfileCard<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfileCardsControllerGetProfileCardQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 유저 프로필 카드를 업데이트 합니다. RequestBody 의 모든 값은 Optional 하며, 주입한 값만 업데이트 합니다.
 *
 * links 는 전체 교체(넘긴 목록으로 덮어씀)이며, 각 항목 type 매핑은 다음과 같습니다.
 * 0: EMAIL, 1: INSTAGRAM, 2: GITHUB, 3: LINKEDIN, 4: BEHANCE, 5: NOTION, 6: WEBSITE
 *
 * experiences 도 전체 교체입니다(넘긴 목록으로 기존 경험을 통째로 덮어씀).
 *
 * ★ 응답은 갱신된 관계까지 포함한 완전한 카드(단건 조회와 동일 형태)이며,
 *   experiences 는 전체를 포함합니다.
 * @summary 유저 프로필 카드 업데이트
 */
export const profileCardsControllerUpdateProfileCard = (
  id: string,
  updateProfileCardDto: BodyType<UpdateProfileCardDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardsControllerUpdateProfileCard200>(
    {
      url: `/profile-cards/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProfileCardDto,
      signal,
    },
    options,
  );
};

export const getProfileCardsControllerUpdateProfileCardMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
    TError,
    { id: string; data: BodyType<UpdateProfileCardDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
  TError,
  { id: string; data: BodyType<UpdateProfileCardDto> },
  TContext
> => {
  const mutationKey = ["profileCardsControllerUpdateProfileCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
    { id: string; data: BodyType<UpdateProfileCardDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return profileCardsControllerUpdateProfileCard(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCardsControllerUpdateProfileCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>
>;
export type ProfileCardsControllerUpdateProfileCardMutationBody =
  BodyType<UpdateProfileCardDto>;
export type ProfileCardsControllerUpdateProfileCardMutationError =
  ErrorType<void>;

/**
 * @summary 유저 프로필 카드 업데이트
 */
export const useProfileCardsControllerUpdateProfileCard = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
      TError,
      { id: string; data: BodyType<UpdateProfileCardDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
  TError,
  { id: string; data: BodyType<UpdateProfileCardDto> },
  TContext
> => {
  return useMutation(
    getProfileCardsControllerUpdateProfileCardMutationOptions(options),
    queryClient,
  );
};
/**
 * 로그인한 유저 본인이 소유한 프로필 카드를 삭제합니다.
 * 본인 소유가 아니거나 존재하지 않으면 404 를 반환합니다.
 *
 * ★ 기본(Default) 카드는 다른 카드 생성의 원본(seed)이므로 삭제할 수 없으며 400 을 반환합니다.
 *   카드에 연결된 경험/스킬/관심사/링크/스크랩은 함께 정리됩니다.
 * @summary 유저 프로필 카드 삭제
 */
export const profileCardsControllerDeleteProfileCard = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardsControllerDeleteProfileCard200>(
    { url: `/profile-cards/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getProfileCardsControllerDeleteProfileCardMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCardsControllerDeleteProfileCard>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCardsControllerDeleteProfileCard>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["profileCardsControllerDeleteProfileCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCardsControllerDeleteProfileCard>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return profileCardsControllerDeleteProfileCard(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCardsControllerDeleteProfileCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerDeleteProfileCard>>
>;

export type ProfileCardsControllerDeleteProfileCardMutationError =
  ErrorType<void>;

/**
 * @summary 유저 프로필 카드 삭제
 */
export const useProfileCardsControllerDeleteProfileCard = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCardsControllerDeleteProfileCard>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCardsControllerDeleteProfileCard>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getProfileCardsControllerDeleteProfileCardMutationOptions(options),
    queryClient,
  );
};
