/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateProfileCardDto,
  ProfileCardResponse,
  ProfileCardsControllerCreateProfileCard200,
  ProfileCardsControllerGetProfileCard200,
  ProfileCardsControllerGetProfileCards200,
  ProfileCardsControllerGetProfileCardsParams,
  UpdateProfileCardDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 유저 프로필 카드 목록 조회
 */
export const profileCardsControllerGetProfileCards = (
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardsControllerGetProfileCards200>(
    { url: `/profile-cards`, method: "GET", params, signal },
    options,
  );
};

export const getProfileCardsControllerGetProfileCardsQueryKey = (
  params?: ProfileCardsControllerGetProfileCardsParams,
) => {
  return [`/profile-cards`, ...(params ? [params] : [])] as const;
};

export const getProfileCardsControllerGetProfileCardsQueryOptions = <
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProfileCardsControllerGetProfileCardsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>
  > = ({ signal }) =>
    profileCardsControllerGetProfileCards(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileCardsControllerGetProfileCardsQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>
>;
export type ProfileCardsControllerGetProfileCardsQueryError = ErrorType<void>;

export function useProfileCardsControllerGetProfileCards<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
          TError,
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardsControllerGetProfileCards<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
          TError,
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardsControllerGetProfileCards<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 유저 프로필 카드 목록 조회
 */

export function useProfileCardsControllerGetProfileCards<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
  TError = ErrorType<void>,
>(
  params: ProfileCardsControllerGetProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCards>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfileCardsControllerGetProfileCardsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 유저 프로필 카드를 생성합니다. 동작 방식은 두 가지로 나뉩니다.
 *
 * 1. 유저의 Default 프로필 카드가 없는 경우 (온보딩)
 * 2. 유저의 Default 프로필 카드가 있는 경우 (추후 카드 생성 시점)
 * @summary 유저 프로필 카드 생성
 */
export const profileCardsControllerCreateProfileCard = (
  createProfileCardDto: BodyType<CreateProfileCardDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardsControllerCreateProfileCard200>(
    {
      url: `/profile-cards`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createProfileCardDto,
      signal,
    },
    options,
  );
};

export const getProfileCardsControllerCreateProfileCardMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
    TError,
    { data: BodyType<CreateProfileCardDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
  TError,
  { data: BodyType<CreateProfileCardDto> },
  TContext
> => {
  const mutationKey = ["profileCardsControllerCreateProfileCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
    { data: BodyType<CreateProfileCardDto> }
  > = (props) => {
    const { data } = props ?? {};

    return profileCardsControllerCreateProfileCard(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCardsControllerCreateProfileCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>
>;
export type ProfileCardsControllerCreateProfileCardMutationBody =
  BodyType<CreateProfileCardDto>;
export type ProfileCardsControllerCreateProfileCardMutationError =
  ErrorType<void>;

/**
 * @summary 유저 프로필 카드 생성
 */
export const useProfileCardsControllerCreateProfileCard = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
      TError,
      { data: BodyType<CreateProfileCardDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCardsControllerCreateProfileCard>>,
  TError,
  { data: BodyType<CreateProfileCardDto> },
  TContext
> => {
  return useMutation(
    getProfileCardsControllerCreateProfileCardMutationOptions(options),
    queryClient,
  );
};
export const profileCardsControllerGetProfileCard = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardsControllerGetProfileCard200>(
    { url: `/profile-cards/${id}`, method: "GET", signal },
    options,
  );
};

export const getProfileCardsControllerGetProfileCardQueryKey = (id: string) => {
  return [`/profile-cards/${id}`] as const;
};

export const getProfileCardsControllerGetProfileCardQueryOptions = <
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProfileCardsControllerGetProfileCardQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>
  > = ({ signal }) =>
    profileCardsControllerGetProfileCard(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileCardsControllerGetProfileCardQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>
>;
export type ProfileCardsControllerGetProfileCardQueryError = ErrorType<void>;

export function useProfileCardsControllerGetProfileCard<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
          TError,
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardsControllerGetProfileCard<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
          TError,
          Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardsControllerGetProfileCard<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useProfileCardsControllerGetProfileCard<
  TData = Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardsControllerGetProfileCard>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfileCardsControllerGetProfileCardQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 유저 프로필 카드를 업데이트 합니다. RequestBody 의 모든 값은 Optional 하며, 주입한 값만 업데이트 합니다.
 * @summary 유저 프로필 카드 업데이트
 */
export const profileCardsControllerUpdateProfileCard = (
  id: string,
  updateProfileCardDto: BodyType<UpdateProfileCardDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardResponse>(
    {
      url: `/profile-cards/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProfileCardDto,
      signal,
    },
    options,
  );
};

export const getProfileCardsControllerUpdateProfileCardMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
    TError,
    { id: string; data: BodyType<UpdateProfileCardDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
  TError,
  { id: string; data: BodyType<UpdateProfileCardDto> },
  TContext
> => {
  const mutationKey = ["profileCardsControllerUpdateProfileCard"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
    { id: string; data: BodyType<UpdateProfileCardDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return profileCardsControllerUpdateProfileCard(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCardsControllerUpdateProfileCardMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>
>;
export type ProfileCardsControllerUpdateProfileCardMutationBody =
  BodyType<UpdateProfileCardDto>;
export type ProfileCardsControllerUpdateProfileCardMutationError =
  ErrorType<void>;

/**
 * @summary 유저 프로필 카드 업데이트
 */
export const useProfileCardsControllerUpdateProfileCard = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
      TError,
      { id: string; data: BodyType<UpdateProfileCardDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCardsControllerUpdateProfileCard>>,
  TError,
  { id: string; data: BodyType<UpdateProfileCardDto> },
  TContext
> => {
  return useMutation(
    getProfileCardsControllerUpdateProfileCardMutationOptions(options),
    queryClient,
  );
};
