/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { AuthControllerLogout200Data } from "./authControllerLogout200Data";
import type { ResponseSuccess } from "./responseSuccess";

export type AuthControllerLogout200 = ResponseSuccess & {
  data: AuthControllerLogout200Data;
};
