/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */
import type { CardBackgroundImageResponse } from "./cardBackgroundImageResponse";
import type { ResponseSuccess } from "./responseSuccess";

export type CardBackgroundImagesControllerCreate200 = ResponseSuccess & {
  data: CardBackgroundImageResponse;
};
