/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */
import type { FormattedDate } from "./formattedDate";

export interface CardBackgroundImageResponse {
  id: number;
  /** base URL (뒤에 /origin.webp · /282x400.webp 붙여 접근) */
  imageUrl: string;
  createdAt: FormattedDate;
}
