/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { ProfileCardResponse } from "./profileCardResponse";

export interface CollectionResponse {
  /** 스크랩 ID */
  id: number;
  /** 담긴 보관함(그룹) ID */
  groupId: number;
  /** 스크랩된 프로필 카드 */
  card: ProfileCardResponse;
}
