/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */

export interface CollectionGroupResponse {
  /** 보관함(그룹) ID */
  id: number;
  /** 보관함 이름 */
  name: string;
  /** 보관함에 담긴 스크랩 수 */
  itemCount: number;
}
