/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */
import type { CollectionResponse } from "./collectionResponse";
import type { PaginationMetadata } from "./paginationMetadata";
import type { PaginationType } from "./paginationType";

export type CollectionGroupsControllerGetCollectionItems200Data =
  PaginationType & {
    items?: CollectionResponse[];
    metadata?: PaginationMetadata;
  };
