/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { ConnectionRequestsControllerCancelRequest200Data } from "./connectionRequestsControllerCancelRequest200Data";
import type { ResponseSuccess } from "./responseSuccess";

export type ConnectionRequestsControllerCancelRequest200 = ResponseSuccess & {
  data: ConnectionRequestsControllerCancelRequest200Data;
};
