/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */

/**
 * 0: 대기, 1: 수락, 2: 거절, 3: 취소
 */
export type ConnectionRequestResponseStatus =
  (typeof ConnectionRequestResponseStatus)[keyof typeof ConnectionRequestResponseStatus];

export const ConnectionRequestResponseStatus = {
  NUMBER_0: 0,
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
