/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { FormattedDate } from "./formattedDate";
import type { ProfileCardResponse } from "./profileCardResponse";

export interface ConnectionResponse {
  /** 연결(보관) ID (ULID) */
  id: string;
  /** 연결된 상대 카드 (성립 시점 스냅샷) */
  card: ProfileCardResponse;
  /** 연결 요청 시 첨부한 메시지 */
  message: string | null;
  /** 연결 성립 시각 */
  connectedAt: FormattedDate;
}
