/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { ConnectionRequestResponseStatus } from "./connectionRequestResponseStatus";
import type { FormattedDate } from "./formattedDate";
import type { ProfileCardResponse } from "./profileCardResponse";

export interface ConnectionRequestResponse {
  /** 연결 요청 ID (ULID) */
  id: string;
  /** 0: 대기, 1: 수락, 2: 거절, 3: 취소 */
  status: ConnectionRequestResponseStatus;
  /** 연결 요청 첨부 메시지 */
  message: string | null;
  /** 상대 카드. 받은 요청함이면 요청을 보낸 카드, 보낸 요청함이면 요청을 받은 카드. */
  card: ProfileCardResponse;
  createdAt: FormattedDate;
}
