/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */

export interface CreateCardBackgroundImageDto {
  /**
   * 업로드 API 가 반환한 base URL (뒤에 /origin.webp · /282x400.webp 붙여 접근)
   * @maxLength 500
   */
  imageUrl: string;
}
