/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */

export interface CreateProfileCardDto {
  /**
   * 템플릿 ID (number)
   * @minimum 1
   */
  templateId: number;
  /**
   * 프로필 카드 이미지 URL
   * @minLength 10
   * @maxLength 500
   */
  cardImageUrl?: string;
}
