/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */

export interface CreateCollectionDto {
  /**
   * 스크랩할 프로필 카드 ID (ULID, 26자)
   * @minLength 26
   * @maxLength 26
   */
  cardId: string;
  /**
   * 담을 보관함(그룹) ID
   * @minimum 1
   */
  groupId: number;
}
