/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */

export interface CreatePurposeDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  name: string;
  /**
   * 표시 순서
   * @minimum 0
   */
  sortOrder: number;
}
