/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */

export interface CreateConnectionRequestDto {
  /**
   * 요청을 보내는 내 카드 ID (ULID, 26자)
   * @minLength 26
   * @maxLength 26
   */
  requesterCardId: string;
  /**
   * 요청을 받는 상대 카드 ID (ULID, 26자)
   * @minLength 26
   * @maxLength 26
   */
  receiverCardId: string;
  /**
   * 연결 요청 첨부 메시지 (최대 500자)
   * @maxLength 500
   */
  message?: string;
}
