/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.2
 */

export interface CreateProfileCardDto {
  /**
   * 직군(jobType) ID (number)
   * @minimum 1
   */
  jobTypeId: number;
  /**
   * 목적 ID (팀 빌딩/친목/커피챗 등)
   * @minimum 1
   */
  purposeId?: number;
}
