/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { InterestsControllerFindAllOrder } from "./interestsControllerFindAllOrder";
import type { InterestsControllerFindAllSort } from "./interestsControllerFindAllSort";

export type InterestsControllerFindAllParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 정렬할 필드명
   */
  sort?: InterestsControllerFindAllSort;
  order?: InterestsControllerFindAllOrder;
  /**
   * name 검색어 (부분 일치)
   */
  search?: string;
};
