/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.2
 */
import type { JobTypeResponse } from "./jobTypeResponse";
import type { ResponseSuccess } from "./responseSuccess";

export type JobTypeControllerCreate200 = ResponseSuccess & {
  data: JobTypeResponse;
};
