/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */

export type JobTypeControllerFindAllSort =
  (typeof JobTypeControllerFindAllSort)[keyof typeof JobTypeControllerFindAllSort];

export const JobTypeControllerFindAllSort = {
  id: "id",
  name: "name",
} as const;
