/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */
import type { NotificationsControllerFindAllOrder } from "./notificationsControllerFindAllOrder";
import type { NotificationsControllerFindAllSort } from "./notificationsControllerFindAllSort";

export type NotificationsControllerFindAllParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 정렬할 필드명
   */
  sort?: NotificationsControllerFindAllSort;
  order?: NotificationsControllerFindAllOrder;
  /**
   * 읽음 여부 필터링
   */
  isRead?: boolean;
};
