/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */
import type { NotificationsControllerFindAll200Data } from "./notificationsControllerFindAll200Data";
import type { ResponseSuccess } from "./responseSuccess";

export type NotificationsControllerFindAll200 = ResponseSuccess & {
  data: NotificationsControllerFindAll200Data;
};
