/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */

/**
 * 알림 타입별 상세 데이터
 */
export type NotificationResponsePayload = { [key: string]: unknown };
