/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */
import type { FormattedDate } from "./formattedDate";
import type { NotificationResponsePayload } from "./notificationResponsePayload";
import type { NotificationResponseType } from "./notificationResponseType";

export interface NotificationResponse {
  id: string;
  /** 1: 수락됨, 2: 거절됨 */
  type: NotificationResponseType;
  /** 알림 타입별 상세 데이터 */
  payload: NotificationResponsePayload;
  readAt: FormattedDate | null;
  createdAt: FormattedDate;
}
