/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */

/**
 * 1: 수락됨, 2: 거절됨
 */
export type NotificationResponseType =
  (typeof NotificationResponseType)[keyof typeof NotificationResponseType];

export const NotificationResponseType = {
  NUMBER_1: 1,
  NUMBER_2: 2,
  NUMBER_3: 3,
} as const;
