/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import type { PaginationMetadataOrder } from "./paginationMetadataOrder";

export interface PaginationMetadata {
  page: number;
  limit: number;
  /** 정렬한 필드명 */
  sort: string;
  order: PaginationMetadataOrder;
  /** 전체 데이터 수 */
  total: number;
}
