/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */

export type PaginationMetadataOrder =
  (typeof PaginationMetadataOrder)[keyof typeof PaginationMetadataOrder];

export const PaginationMetadataOrder = {
  asc: "asc",
  desc: "desc",
} as const;
