/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */

export interface ProfileCardExperienceInputDto {
  /**
   * 경험 제목
   * @minLength 2
   * @maxLength 500
   */
  title: string;
  /**
   * 경험 설명
   * @minLength 2
   * @maxLength 2000
   */
  description: string;
  /**
   * 관련 url
   * @maxLength 500
   */
  relatedUrl?: string;
  /**
   * 정렬 순서 (그냥 프론트애서 표시 순서), 대표이면 1이고, 그렇지 않다면 2부터 시작
   * @minimum 1
   * @maximum 10
   */
  sortOrder: number;
}
