/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import type { ProfileCardTemplatesControllerFindAll200Data } from "./profileCardTemplatesControllerFindAll200Data";
import type { ResponseSuccess } from "./responseSuccess";

export type ProfileCardTemplatesControllerFindAll200 = ResponseSuccess & {
  data: ProfileCardTemplatesControllerFindAll200Data;
};
