/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import type { JobTypeResponse } from "./jobTypeResponse";
import type { TemplateItemResponse } from "./templateItemResponse";

export interface ProfileCardTemplateResponse {
  id: number;
  jobType: JobTypeResponse;
  version: number;
  /** true = 현재 활성 버전 */
  isActive: boolean | null;
  items: TemplateItemResponse[];
}
