/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */

export interface ProfileExperienceResponse {
  /**
   * 경험 제목
   * @maxLength 500
   */
  title: string;
  /**
   * 경험 설명
   * @maxLength 2000
   */
  description: string;
  /**
   * 관련 url
   * @maxLength 500
   */
  relatedUrl: string | null;
  /**
   * 경험 순서 (대표 경험은 0, 나머지는 1부터 시작)
   * @minimum 0
   */
  sortOrder: number;
}
