/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */

export interface ProfileCardExperienceInputDto {
  /**
   * 경험 제목
   * @minLength 2
   * @maxLength 500
   */
  title: string;
  /**
   * 경험 설명
   * @minLength 2
   * @maxLength 2000
   */
  description: string;
  /**
   * 관련 url
   * @maxLength 500
   */
  relatedUrl?: string;
  /**
   * 정렬 순서 (프론트 표시 순서). 대표 경험은 0, 나머지는 1부터 시작
   * @minimum 0
   * @maximum 10
   */
  sortOrder: number;
}
