/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import type { ProfileCardTemplatesControllerFindAllOrder } from "./profileCardTemplatesControllerFindAllOrder";
import type { ProfileCardTemplatesControllerFindAllSort } from "./profileCardTemplatesControllerFindAllSort";

export type ProfileCardTemplatesControllerFindAllParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 정렬할 필드명
   */
  sort?: ProfileCardTemplatesControllerFindAllSort;
  order?: ProfileCardTemplatesControllerFindAllOrder;
  /**
   * 직군(jobType) ID 로 필터 (생략 시 전체 조회)
   * @minimum 1
   */
  jobTypeId?: number;
};
