/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import type { AffiliationStatusResponse } from "./affiliationStatusResponse";
import type { FormattedDate } from "./formattedDate";
import type { PersonalityResponse } from "./personalityResponse";
import type { ProfileCardInterestResponse } from "./profileCardInterestResponse";
import type { SkillResponse } from "./skillResponse";

export interface ProfileCardResponse {
  id: string;
  nickname: string;
  cardImageUrl: string | null;
  description: string;
  affiliation: string | null;
  isActive: boolean;
  isDefault: boolean;
  userId: string;
  createdAt: FormattedDate;
  updatedAt: FormattedDate;
  skills?: SkillResponse[];
  interests?: ProfileCardInterestResponse[];
  personality?: PersonalityResponse | null;
  affiliationStatus?: AffiliationStatusResponse | null;
}
