/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { ProfileCardLinkInputDtoType } from "./profileCardLinkInputDtoType";

export interface ProfileCardLinkInputDto {
  /** 링크 종류 — 0: EMAIL, 1: INSTAGRAM, 2: GITHUB, 3: LINKEDIN, 4: BEHANCE, 5: NOTION, 6: WEBSITE */
  type: ProfileCardLinkInputDtoType;
  /**
   * 링크(URL) 또는 이메일 값
   * @minLength 1
   * @maxLength 500
   */
  value: string;
}
