/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */
import type { PublicProfileCardsControllerGetPublicProfileCardsOrder } from "./publicProfileCardsControllerGetPublicProfileCardsOrder";
import type { PublicProfileCardsControllerGetPublicProfileCardsSort } from "./publicProfileCardsControllerGetPublicProfileCardsSort";

export type PublicProfileCardsControllerGetPublicProfileCardsParams = {
  /**
   * @minimum 1
   */
  page?: number;
  /**
   * @minimum 1
   * @maximum 100
   */
  limit?: number;
  /**
   * 정렬할 필드명
   */
  sort?: PublicProfileCardsControllerGetPublicProfileCardsSort;
  order?: PublicProfileCardsControllerGetPublicProfileCardsOrder;
  /**
   * 목적 필터
   * @minimum 1
   */
  purpose?: number;
  /**
   * 직군 필터
   * @minimum 1
   */
  jobTypeId?: number;
  /**
   * 상태 필터
   * @minimum 1
   */
  affiliationStatusId?: number;
  /**
   * 검색 키워드
   */
  keywords?: string;
};
