/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */
import type { PaginationMetadata } from "./paginationMetadata";
import type { PaginationType } from "./paginationType";
import type { PurposeResponse } from "./purposeResponse";

export type PurposesControllerFindAll200Data = PaginationType & {
  items?: PurposeResponse[];
  metadata?: PaginationMetadata;
};
