/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */
import type { PurposesControllerFindAll200Data } from "./purposesControllerFindAll200Data";
import type { ResponseSuccess } from "./responseSuccess";

export type PurposesControllerFindAll200 = ResponseSuccess & {
  data: PurposesControllerFindAll200Data;
};
