/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { ResponseSuccess } from "./responseSuccess";
import type { SkillsControllerRemove200Data } from "./skillsControllerRemove200Data";

export type SkillsControllerRemove200 = ResponseSuccess & {
  data: SkillsControllerRemove200Data;
};
