/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import type { ResponseSuccess } from "./responseSuccess";
import type { SkillsControllerFindAll200Data } from "./skillsControllerFindAll200Data";

export type SkillsControllerFindAll200 = ResponseSuccess & {
  data: SkillsControllerFindAll200Data;
};
