/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */
import type { SkillCategoryResponse } from "./skillCategoryResponse";

export interface SkillResponse {
  id: number;
  name: string;
  category: SkillCategoryResponse;
}
