/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */

export interface TemplateItemResponse {
  id: number;
  label: string;
  description: string;
  /** 0: SHORT_TEXT, 1: LONG_TEXT, 2: LINK, 3: NUMBER */
  type: number;
}
