/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */

export interface UpdateProfileCardDto {
  /**
   * 스킬 ID 목록
   * @items.minimum 1
   */
  skillIds?: number[];
  /**
   * 관심사 ID 목록
   * @items.minimum 1
   */
  interestIds?: number[];
  /**
   * 개성 ID (카드당 하나만 선택)
   * @minimum 1
   */
  personalityId?: number;
  /** 한 줄 소개 */
  description?: string;
  /**
   * 소속 상태
   * @minimum 1
   */
  affiliationStatusId?: number;
  /** 소속 명칭 */
  affiliation?: string;
}
