/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.2
 */

export interface UpdateSkillDto {
  /**
   * 스킬 이름 (고유)
   * @maxLength 100
   */
  name?: string;
  /**
   * 스킬 카테고리 ID
   * @minimum 1
   */
  categoryId?: number;
  /**
   * 이 스킬이 속한 직군 ID 목록. 전 직군 공통 스킬이면 모든 직군 ID 를 넣습니다. (빈 배열 불가 — 매핑이 없는 상태는 "아직 지정하지 않음" 과 구분되지 않습니다)
   * @minItems 1
   * @items.minimum 1
   */
  jobTypeIds?: number[];
}
