/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.0.1
 */
import type { ProfileCardLinkInputDto } from "./profileCardLinkInputDto";

export interface UpdateDefaultProfileCardDto {
  /**
   * 프로필 카드 닉네임 (1 ~ 255자)
   * @minLength 1
   * @maxLength 255
   */
  nickname?: string;
  /** 링크 목록 (전체 교체: 넘긴 목록으로 덮어씀). 각 항목 type — 0: EMAIL, 1: INSTAGRAM, 2: GITHUB, 3: LINKEDIN, 4: BEHANCE, 5: NOTION, 6: WEBSITE */
  links?: ProfileCardLinkInputDto[];
}
