/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */

export interface UpdateSkillDto {
  /**
   * 스킬 이름 (고유)
   * @maxLength 100
   */
  name?: string;
  /**
   * 스킬 카테고리 ID
   * @minimum 1
   */
  categoryId?: number;
}
