/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */

export interface UploadImageResponse {
  /** uuid 까지의 base URL. `${url}/origin.webp` · `${url}/72.webp` 처럼 접근 */
  url: string;
}
