/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.2
 */
import type { FormattedDate } from "./formattedDate";

export interface UserResponse {
  /** 유저 ID */
  id: string;
  /** 유저 이름 */
  name: string;
  /** 유저 닉네임 */
  nickname: string;
  email: string;
  createdAt: FormattedDate;
  updatedAt: FormattedDate;
}
