/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import type { AdminUserResponse } from "./adminUserResponse";
import type { PaginationMetadata } from "./paginationMetadata";
import type { PaginationType } from "./paginationType";

export type UsersControllerGetAllUsers200Data = PaginationType & {
  items?: AdminUserResponse[];
  metadata?: PaginationMetadata;
};
