/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  PublicProfileCardsControllerGetPublicProfileCard200,
  PublicProfileCardsControllerGetPublicProfileCards200,
  PublicProfileCardsControllerGetPublicProfileCardsParams,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 인증 없이 카드 ID 로 프로필 카드를 조회합니다. (카드 공유용)
 * @summary 프로필 카드 단건 조회 (public)
 */
export const publicProfileCardsControllerGetPublicProfileCard = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PublicProfileCardsControllerGetPublicProfileCard200>(
    { url: `/public/profile-cards/${id}`, method: "GET", signal },
    options,
  );
};

export const getPublicProfileCardsControllerGetPublicProfileCardQueryKey = (
  id: string,
) => {
  return [`/public/profile-cards/${id}`] as const;
};

export const getPublicProfileCardsControllerGetPublicProfileCardQueryOptions = <
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
  >,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getPublicProfileCardsControllerGetPublicProfileCardQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>>
  > = ({ signal }) =>
    publicProfileCardsControllerGetPublicProfileCard(
      id,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<
      ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
    >,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PublicProfileCardsControllerGetPublicProfileCardQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>>
  >;
export type PublicProfileCardsControllerGetPublicProfileCardQueryError =
  ErrorType<void>;

export function usePublicProfileCardsControllerGetPublicProfileCard<
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
  >,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
          >,
          TError,
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicProfileCardsControllerGetPublicProfileCard<
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
  >,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
          >,
          TError,
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicProfileCardsControllerGetPublicProfileCard<
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
  >,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 프로필 카드 단건 조회 (public)
 */

export function usePublicProfileCardsControllerGetPublicProfileCard<
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
  >,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCard>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getPublicProfileCardsControllerGetPublicProfileCardQueryOptions(
      id,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 인증 없이 활성(isActive) 프로필 카드 목록을 조회합니다.
 * purpose / jobTypeId / affiliationStatusId 필터와 keywords(닉네임) 검색을 지원합니다.
 * @summary 공개 프로필 카드 목록 조회 (public)
 */
export const publicProfileCardsControllerGetPublicProfileCards = (
  params: PublicProfileCardsControllerGetPublicProfileCardsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PublicProfileCardsControllerGetPublicProfileCards200>(
    { url: `/public/profile-cards`, method: "GET", params, signal },
    options,
  );
};

export const getPublicProfileCardsControllerGetPublicProfileCardsQueryKey = (
  params?: PublicProfileCardsControllerGetPublicProfileCardsParams,
) => {
  return [`/public/profile-cards`, ...(params ? [params] : [])] as const;
};

export const getPublicProfileCardsControllerGetPublicProfileCardsQueryOptions =
  <
    TData = Awaited<
      ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
    >,
    TError = ErrorType<unknown>,
  >(
    params: PublicProfileCardsControllerGetPublicProfileCardsParams,
    options?: {
      query?: Partial<
        UseQueryOptions<
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
          >,
          TError,
          TData
        >
      >;
      request?: SecondParameter<typeof customInstance>;
    },
  ) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
      queryOptions?.queryKey ??
      getPublicProfileCardsControllerGetPublicProfileCardsQueryKey(params);

    const queryFn: QueryFunction<
      Awaited<
        ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
      >
    > = ({ signal }) =>
      publicProfileCardsControllerGetPublicProfileCards(
        params,
        requestOptions,
        signal,
      );

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
      Awaited<
        ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
      >,
      TError,
      TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
  };

export type PublicProfileCardsControllerGetPublicProfileCardsQueryResult =
  NonNullable<
    Awaited<
      ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
    >
  >;
export type PublicProfileCardsControllerGetPublicProfileCardsQueryError =
  ErrorType<unknown>;

export function usePublicProfileCardsControllerGetPublicProfileCards<
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
  >,
  TError = ErrorType<unknown>,
>(
  params: PublicProfileCardsControllerGetPublicProfileCardsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
          >,
          TError,
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicProfileCardsControllerGetPublicProfileCards<
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
  >,
  TError = ErrorType<unknown>,
>(
  params: PublicProfileCardsControllerGetPublicProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
          >,
          TError,
          Awaited<
            ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePublicProfileCardsControllerGetPublicProfileCards<
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
  >,
  TError = ErrorType<unknown>,
>(
  params: PublicProfileCardsControllerGetPublicProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 공개 프로필 카드 목록 조회 (public)
 */

export function usePublicProfileCardsControllerGetPublicProfileCards<
  TData = Awaited<
    ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
  >,
  TError = ErrorType<unknown>,
>(
  params: PublicProfileCardsControllerGetPublicProfileCardsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof publicProfileCardsControllerGetPublicProfileCards>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getPublicProfileCardsControllerGetPublicProfileCardsQueryOptions(
      params,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
