/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  UpdateProfileDto,
  UsersControllerGetAllUsers200,
  UsersControllerGetAllUsersParams,
  UsersControllerGetMe200,
  UsersControllerUpdateMe200,
  UsersControllerWithdraw200,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 모든 유저를 페이지네이션으로 조회합니다. 탈퇴한 유저도 포함됩니다. ADMIN 권한이 필요합니다.
 *
 * **요청 query**
 * - page, limit, sort, order: 페이지네이션 옵션
 *
 * **응답 body**
 * - items: 유저 목록 (각 항목에 마지막 로그인 시각 lastLoginAt, 탈퇴 시각 deletedAt 포함)
 * - metadata: 페이지네이션 정보
 * @summary 전체 유저 조회 (관리자)
 */
export const usersControllerGetAllUsers = (
  params: UsersControllerGetAllUsersParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UsersControllerGetAllUsers200>(
    { url: `/users`, method: "GET", params, signal },
    options,
  );
};

export const getUsersControllerGetAllUsersQueryKey = (
  params?: UsersControllerGetAllUsersParams,
) => {
  return [`/users`, ...(params ? [params] : [])] as const;
};

export const getUsersControllerGetAllUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
  TError = ErrorType<void>,
>(
  params: UsersControllerGetAllUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getUsersControllerGetAllUsersQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetAllUsers>>
  > = ({ signal }) =>
    usersControllerGetAllUsers(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetAllUsersQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetAllUsers>>
>;
export type UsersControllerGetAllUsersQueryError = ErrorType<void>;

export function useUsersControllerGetAllUsers<
  TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
  TError = ErrorType<void>,
>(
  params: UsersControllerGetAllUsersParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetAllUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetAllUsers<
  TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
  TError = ErrorType<void>,
>(
  params: UsersControllerGetAllUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetAllUsers>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetAllUsers<
  TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
  TError = ErrorType<void>,
>(
  params: UsersControllerGetAllUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 전체 유저 조회 (관리자)
 */

export function useUsersControllerGetAllUsers<
  TData = Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
  TError = ErrorType<void>,
>(
  params: UsersControllerGetAllUsersParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetAllUsers>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUsersControllerGetAllUsersQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 현재 로그인한 사용자의 프로필 정보를 반환합니다. User 이상의 역할이 필합니다.
 * @summary 내 정보 조회
 */
export const usersControllerGetMe = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UsersControllerGetMe200>(
    { url: `/users/me`, method: "GET", signal },
    options,
  );
};

export const getUsersControllerGetMeQueryKey = () => {
  return [`/users/me`] as const;
};

export const getUsersControllerGetMeQueryOptions = <
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof usersControllerGetMe>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getUsersControllerGetMeQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof usersControllerGetMe>>
  > = ({ signal }) => usersControllerGetMe(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof usersControllerGetMe>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type UsersControllerGetMeQueryResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerGetMe>>
>;
export type UsersControllerGetMeQueryError = ErrorType<void>;

export function useUsersControllerGetMe<
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetMe>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetMe<
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetMe>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersControllerGetMe>>,
          TError,
          Awaited<ReturnType<typeof usersControllerGetMe>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useUsersControllerGetMe<
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 정보 조회
 */

export function useUsersControllerGetMe<
  TData = Awaited<ReturnType<typeof usersControllerGetMe>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof usersControllerGetMe>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getUsersControllerGetMeQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * nickname 의 길이는 1 ~ 255 입니다.
 * @summary 유저 정보 업데이트
 */
export const usersControllerUpdateMe = (
  updateProfileDto: BodyType<UpdateProfileDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UsersControllerUpdateMe200>(
    {
      url: `/users/me`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProfileDto,
      signal,
    },
    options,
  );
};

export const getUsersControllerUpdateMeMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerUpdateMe>>,
    TError,
    { data: BodyType<UpdateProfileDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerUpdateMe>>,
  TError,
  { data: BodyType<UpdateProfileDto> },
  TContext
> => {
  const mutationKey = ["usersControllerUpdateMe"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerUpdateMe>>,
    { data: BodyType<UpdateProfileDto> }
  > = (props) => {
    const { data } = props ?? {};

    return usersControllerUpdateMe(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerUpdateMeMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerUpdateMe>>
>;
export type UsersControllerUpdateMeMutationBody = BodyType<UpdateProfileDto>;
export type UsersControllerUpdateMeMutationError = ErrorType<void>;

/**
 * @summary 유저 정보 업데이트
 */
export const useUsersControllerUpdateMe = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerUpdateMe>>,
      TError,
      { data: BodyType<UpdateProfileDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerUpdateMe>>,
  TError,
  { data: BodyType<UpdateProfileDto> },
  TContext
> => {
  return useMutation(
    getUsersControllerUpdateMeMutationOptions(options),
    queryClient,
  );
};
/**
 * 현재 로그인한 사용자를 탈퇴 처리합니다. 계정 정보는 일정 기간 보관됩니다.
 *
 * - 소셜 인증 연결이 해제되어 더 이상 로그인할 수 없습니다.
 * - 모든 기기의 로그인 세션이 종료되고 리프레시 토큰 쿠키가 제거됩니다.
 * - 동일한 이메일/소셜 계정으로 다시 가입할 수 있습니다.
 * @summary 회원 탈퇴
 */
export const usersControllerWithdraw = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<UsersControllerWithdraw200>(
    { url: `/users/me`, method: "DELETE", signal },
    options,
  );
};

export const getUsersControllerWithdrawMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof usersControllerWithdraw>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof usersControllerWithdraw>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["usersControllerWithdraw"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof usersControllerWithdraw>>,
    void
  > = () => {
    return usersControllerWithdraw(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type UsersControllerWithdrawMutationResult = NonNullable<
  Awaited<ReturnType<typeof usersControllerWithdraw>>
>;

export type UsersControllerWithdrawMutationError = ErrorType<void>;

/**
 * @summary 회원 탈퇴
 */
export const useUsersControllerWithdraw = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof usersControllerWithdraw>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof usersControllerWithdraw>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getUsersControllerWithdrawMutationOptions(options),
    queryClient,
  );
};
