/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreatePersonalityDto,
  PersonalitiesControllerCreate200,
  PersonalitiesControllerDelete200,
  PersonalitiesControllerFindAll200,
  PersonalitiesControllerFindAllParams,
  PersonalitiesControllerUpdate200,
  UpdatePersonalityDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * personality 는 createdAt 이 없어 sort 는 id·name 만 허용하며 기본값은 name 입니다.
 * @summary 모든 personalities 를 조회합니다.
 */
export const personalitiesControllerFindAll = (
  params: PersonalitiesControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PersonalitiesControllerFindAll200>(
    { url: `/personalities`, method: "GET", params, signal },
    options,
  );
};

export const getPersonalitiesControllerFindAllQueryKey = (
  params?: PersonalitiesControllerFindAllParams,
) => {
  return [`/personalities`, ...(params ? [params] : [])] as const;
};

export const getPersonalitiesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PersonalitiesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPersonalitiesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof personalitiesControllerFindAll>>
  > = ({ signal }) =>
    personalitiesControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PersonalitiesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof personalitiesControllerFindAll>>
>;
export type PersonalitiesControllerFindAllQueryError = ErrorType<unknown>;

export function usePersonalitiesControllerFindAll<
  TData = Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PersonalitiesControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof personalitiesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePersonalitiesControllerFindAll<
  TData = Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PersonalitiesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof personalitiesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePersonalitiesControllerFindAll<
  TData = Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PersonalitiesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 모든 personalities 를 조회합니다.
 */

export function usePersonalitiesControllerFindAll<
  TData = Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PersonalitiesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof personalitiesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPersonalitiesControllerFindAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary personalities 생성 (ADMIN)
 */
export const personalitiesControllerCreate = (
  createPersonalityDto: BodyType<CreatePersonalityDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PersonalitiesControllerCreate200>(
    {
      url: `/personalities`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPersonalityDto,
      signal,
    },
    options,
  );
};

export const getPersonalitiesControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalitiesControllerCreate>>,
    TError,
    { data: BodyType<CreatePersonalityDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof personalitiesControllerCreate>>,
  TError,
  { data: BodyType<CreatePersonalityDto> },
  TContext
> => {
  const mutationKey = ["personalitiesControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof personalitiesControllerCreate>>,
    { data: BodyType<CreatePersonalityDto> }
  > = (props) => {
    const { data } = props ?? {};

    return personalitiesControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PersonalitiesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof personalitiesControllerCreate>>
>;
export type PersonalitiesControllerCreateMutationBody =
  BodyType<CreatePersonalityDto>;
export type PersonalitiesControllerCreateMutationError = ErrorType<void>;

/**
 * @summary personalities 생성 (ADMIN)
 */
export const usePersonalitiesControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof personalitiesControllerCreate>>,
      TError,
      { data: BodyType<CreatePersonalityDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof personalitiesControllerCreate>>,
  TError,
  { data: BodyType<CreatePersonalityDto> },
  TContext
> => {
  return useMutation(
    getPersonalitiesControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary personalities 수정 (ADMIN)
 */
export const personalitiesControllerUpdate = (
  id: string,
  updatePersonalityDto: BodyType<UpdatePersonalityDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PersonalitiesControllerUpdate200>(
    {
      url: `/personalities/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updatePersonalityDto,
      signal,
    },
    options,
  );
};

export const getPersonalitiesControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalitiesControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdatePersonalityDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof personalitiesControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdatePersonalityDto> },
  TContext
> => {
  const mutationKey = ["personalitiesControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof personalitiesControllerUpdate>>,
    { id: string; data: BodyType<UpdatePersonalityDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return personalitiesControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PersonalitiesControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof personalitiesControllerUpdate>>
>;
export type PersonalitiesControllerUpdateMutationBody =
  BodyType<UpdatePersonalityDto>;
export type PersonalitiesControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary personalities 수정 (ADMIN)
 */
export const usePersonalitiesControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof personalitiesControllerUpdate>>,
      TError,
      { id: string; data: BodyType<UpdatePersonalityDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof personalitiesControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdatePersonalityDto> },
  TContext
> => {
  return useMutation(
    getPersonalitiesControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary personalities 삭제 (ADMIN)
 */
export const personalitiesControllerDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PersonalitiesControllerDelete200>(
    { url: `/personalities/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getPersonalitiesControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof personalitiesControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof personalitiesControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["personalitiesControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof personalitiesControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return personalitiesControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PersonalitiesControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof personalitiesControllerDelete>>
>;

export type PersonalitiesControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary personalities 삭제 (ADMIN)
 */
export const usePersonalitiesControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof personalitiesControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof personalitiesControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPersonalitiesControllerDeleteMutationOptions(options),
    queryClient,
  );
};
