/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AffiliationStatusesControllerCreate200,
  AffiliationStatusesControllerDelete200,
  AffiliationStatusesControllerFindAll200,
  AffiliationStatusesControllerFindAllParams,
  AffiliationStatusesControllerUpdate200,
  CreateAffiliationStatusDto,
  UpdateAffiliationStatusDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * affiliation-status 는 createdAt 이 없어 sort 는 id·name 만 허용하며 기본값은 name 입니다.
 * @summary 모든 affiliation-statuses 를 조회합니다.
 */
export const affiliationStatusesControllerFindAll = (
  params: AffiliationStatusesControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AffiliationStatusesControllerFindAll200>(
    { url: `/affiliation-statuses`, method: "GET", params, signal },
    options,
  );
};

export const getAffiliationStatusesControllerFindAllQueryKey = (
  params?: AffiliationStatusesControllerFindAllParams,
) => {
  return [`/affiliation-statuses`, ...(params ? [params] : [])] as const;
};

export const getAffiliationStatusesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: AffiliationStatusesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getAffiliationStatusesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>
  > = ({ signal }) =>
    affiliationStatusesControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AffiliationStatusesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>
>;
export type AffiliationStatusesControllerFindAllQueryError = ErrorType<unknown>;

export function useAffiliationStatusesControllerFindAll<
  TData = Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: AffiliationStatusesControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAffiliationStatusesControllerFindAll<
  TData = Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: AffiliationStatusesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAffiliationStatusesControllerFindAll<
  TData = Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: AffiliationStatusesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 모든 affiliation-statuses 를 조회합니다.
 */

export function useAffiliationStatusesControllerFindAll<
  TData = Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: AffiliationStatusesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof affiliationStatusesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAffiliationStatusesControllerFindAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary affiliation-statuses 생성 (ADMIN)
 */
export const affiliationStatusesControllerCreate = (
  createAffiliationStatusDto: BodyType<CreateAffiliationStatusDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AffiliationStatusesControllerCreate200>(
    {
      url: `/affiliation-statuses`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createAffiliationStatusDto,
      signal,
    },
    options,
  );
};

export const getAffiliationStatusesControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof affiliationStatusesControllerCreate>>,
    TError,
    { data: BodyType<CreateAffiliationStatusDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof affiliationStatusesControllerCreate>>,
  TError,
  { data: BodyType<CreateAffiliationStatusDto> },
  TContext
> => {
  const mutationKey = ["affiliationStatusesControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof affiliationStatusesControllerCreate>>,
    { data: BodyType<CreateAffiliationStatusDto> }
  > = (props) => {
    const { data } = props ?? {};

    return affiliationStatusesControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AffiliationStatusesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof affiliationStatusesControllerCreate>>
>;
export type AffiliationStatusesControllerCreateMutationBody =
  BodyType<CreateAffiliationStatusDto>;
export type AffiliationStatusesControllerCreateMutationError = ErrorType<void>;

/**
 * @summary affiliation-statuses 생성 (ADMIN)
 */
export const useAffiliationStatusesControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof affiliationStatusesControllerCreate>>,
      TError,
      { data: BodyType<CreateAffiliationStatusDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof affiliationStatusesControllerCreate>>,
  TError,
  { data: BodyType<CreateAffiliationStatusDto> },
  TContext
> => {
  return useMutation(
    getAffiliationStatusesControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary affiliation-statuses 수정 (ADMIN)
 */
export const affiliationStatusesControllerUpdate = (
  id: string,
  updateAffiliationStatusDto: BodyType<UpdateAffiliationStatusDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AffiliationStatusesControllerUpdate200>(
    {
      url: `/affiliation-statuses/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateAffiliationStatusDto,
      signal,
    },
    options,
  );
};

export const getAffiliationStatusesControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof affiliationStatusesControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateAffiliationStatusDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof affiliationStatusesControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateAffiliationStatusDto> },
  TContext
> => {
  const mutationKey = ["affiliationStatusesControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof affiliationStatusesControllerUpdate>>,
    { id: string; data: BodyType<UpdateAffiliationStatusDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return affiliationStatusesControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AffiliationStatusesControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof affiliationStatusesControllerUpdate>>
>;
export type AffiliationStatusesControllerUpdateMutationBody =
  BodyType<UpdateAffiliationStatusDto>;
export type AffiliationStatusesControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary affiliation-statuses 수정 (ADMIN)
 */
export const useAffiliationStatusesControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof affiliationStatusesControllerUpdate>>,
      TError,
      { id: string; data: BodyType<UpdateAffiliationStatusDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof affiliationStatusesControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateAffiliationStatusDto> },
  TContext
> => {
  return useMutation(
    getAffiliationStatusesControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary affiliation-statuses 삭제 (ADMIN)
 */
export const affiliationStatusesControllerDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AffiliationStatusesControllerDelete200>(
    { url: `/affiliation-statuses/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getAffiliationStatusesControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof affiliationStatusesControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof affiliationStatusesControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["affiliationStatusesControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof affiliationStatusesControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return affiliationStatusesControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AffiliationStatusesControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof affiliationStatusesControllerDelete>>
>;

export type AffiliationStatusesControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary affiliation-statuses 삭제 (ADMIN)
 */
export const useAffiliationStatusesControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof affiliationStatusesControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof affiliationStatusesControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getAffiliationStatusesControllerDeleteMutationOptions(options),
    queryClient,
  );
};
