/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateInterestDto,
  InterestsControllerCreate200,
  InterestsControllerDelete200,
  InterestsControllerFindAll200,
  InterestsControllerFindAllParams,
  InterestsControllerUpdate200,
  UpdateInterestDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * interest 는 createdAt 이 없어 sort 는 id·name 만 허용하며 기본값은 name 입니다.
 * @summary 모든 interests 를 조회합니다.
 */
export const interestsControllerFindAll = (
  params: InterestsControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<InterestsControllerFindAll200>(
    { url: `/interests`, method: "GET", params, signal },
    options,
  );
};

export const getInterestsControllerFindAllQueryKey = (
  params?: InterestsControllerFindAllParams,
) => {
  return [`/interests`, ...(params ? [params] : [])] as const;
};

export const getInterestsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof interestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: InterestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof interestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getInterestsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof interestsControllerFindAll>>
  > = ({ signal }) =>
    interestsControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof interestsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type InterestsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof interestsControllerFindAll>>
>;
export type InterestsControllerFindAllQueryError = ErrorType<unknown>;

export function useInterestsControllerFindAll<
  TData = Awaited<ReturnType<typeof interestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: InterestsControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof interestsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof interestsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof interestsControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInterestsControllerFindAll<
  TData = Awaited<ReturnType<typeof interestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: InterestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof interestsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof interestsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof interestsControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useInterestsControllerFindAll<
  TData = Awaited<ReturnType<typeof interestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: InterestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof interestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 모든 interests 를 조회합니다.
 */

export function useInterestsControllerFindAll<
  TData = Awaited<ReturnType<typeof interestsControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: InterestsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof interestsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getInterestsControllerFindAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary interests 생성 (ADMIN)
 */
export const interestsControllerCreate = (
  createInterestDto: BodyType<CreateInterestDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<InterestsControllerCreate200>(
    {
      url: `/interests`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createInterestDto,
      signal,
    },
    options,
  );
};

export const getInterestsControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof interestsControllerCreate>>,
    TError,
    { data: BodyType<CreateInterestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof interestsControllerCreate>>,
  TError,
  { data: BodyType<CreateInterestDto> },
  TContext
> => {
  const mutationKey = ["interestsControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof interestsControllerCreate>>,
    { data: BodyType<CreateInterestDto> }
  > = (props) => {
    const { data } = props ?? {};

    return interestsControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InterestsControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof interestsControllerCreate>>
>;
export type InterestsControllerCreateMutationBody = BodyType<CreateInterestDto>;
export type InterestsControllerCreateMutationError = ErrorType<void>;

/**
 * @summary interests 생성 (ADMIN)
 */
export const useInterestsControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof interestsControllerCreate>>,
      TError,
      { data: BodyType<CreateInterestDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof interestsControllerCreate>>,
  TError,
  { data: BodyType<CreateInterestDto> },
  TContext
> => {
  return useMutation(
    getInterestsControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary interests 수정 (ADMIN)
 */
export const interestsControllerUpdate = (
  id: string,
  updateInterestDto: BodyType<UpdateInterestDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<InterestsControllerUpdate200>(
    {
      url: `/interests/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateInterestDto,
      signal,
    },
    options,
  );
};

export const getInterestsControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof interestsControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateInterestDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof interestsControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateInterestDto> },
  TContext
> => {
  const mutationKey = ["interestsControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof interestsControllerUpdate>>,
    { id: string; data: BodyType<UpdateInterestDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return interestsControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InterestsControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof interestsControllerUpdate>>
>;
export type InterestsControllerUpdateMutationBody = BodyType<UpdateInterestDto>;
export type InterestsControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary interests 수정 (ADMIN)
 */
export const useInterestsControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof interestsControllerUpdate>>,
      TError,
      { id: string; data: BodyType<UpdateInterestDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof interestsControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateInterestDto> },
  TContext
> => {
  return useMutation(
    getInterestsControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary interests 삭제 (ADMIN)
 */
export const interestsControllerDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<InterestsControllerDelete200>(
    { url: `/interests/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getInterestsControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof interestsControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof interestsControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["interestsControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof interestsControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return interestsControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type InterestsControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof interestsControllerDelete>>
>;

export type InterestsControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary interests 삭제 (ADMIN)
 */
export const useInterestsControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof interestsControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof interestsControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getInterestsControllerDeleteMutationOptions(options),
    queryClient,
  );
};
