/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation } from "@tanstack/react-query";
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from "@tanstack/react-query";

import type {
  CollectionsControllerCreateCollection200,
  CollectionsControllerDeleteCollection200,
  CollectionsControllerMoveCollection200,
  CreateCollectionDto,
  UpdateCollectionDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * 프로필 카드를 지정한 보관함(groupId)에 스크랩합니다.
 * 담을 보관함이 본인 소유가 아니거나 존재하지 않으면 404,
 * 카드가 존재하지 않으면 400, 이미 스크랩한 카드면 409 를 반환합니다.
 *
 * ★ 카드는 유저당 1번만 스크랩할 수 있습니다(보관함이 달라도 중복 불가).
 * @summary 카드 스크랩 (보관함에 담기)
 */
export const collectionsControllerCreateCollection = (
  createCollectionDto: BodyType<CreateCollectionDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CollectionsControllerCreateCollection200>(
    {
      url: `/collections`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCollectionDto,
      signal,
    },
    options,
  );
};

export const getCollectionsControllerCreateCollectionMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof collectionsControllerCreateCollection>>,
    TError,
    { data: BodyType<CreateCollectionDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof collectionsControllerCreateCollection>>,
  TError,
  { data: BodyType<CreateCollectionDto> },
  TContext
> => {
  const mutationKey = ["collectionsControllerCreateCollection"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof collectionsControllerCreateCollection>>,
    { data: BodyType<CreateCollectionDto> }
  > = (props) => {
    const { data } = props ?? {};

    return collectionsControllerCreateCollection(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CollectionsControllerCreateCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof collectionsControllerCreateCollection>>
>;
export type CollectionsControllerCreateCollectionMutationBody =
  BodyType<CreateCollectionDto>;
export type CollectionsControllerCreateCollectionMutationError =
  ErrorType<void>;

/**
 * @summary 카드 스크랩 (보관함에 담기)
 */
export const useCollectionsControllerCreateCollection = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof collectionsControllerCreateCollection>>,
      TError,
      { data: BodyType<CreateCollectionDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof collectionsControllerCreateCollection>>,
  TError,
  { data: BodyType<CreateCollectionDto> },
  TContext
> => {
  return useMutation(
    getCollectionsControllerCreateCollectionMutationOptions(options),
    queryClient,
  );
};
/**
 * 스크랩을 다른 보관함으로 이동합니다.
 * 스크랩 또는 이동 대상 보관함이 본인 소유가 아니거나 존재하지 않으면 404 를 반환합니다.
 * @summary 스크랩 보관함 이동
 */
export const collectionsControllerMoveCollection = (
  collectionId: number,
  updateCollectionDto: BodyType<UpdateCollectionDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CollectionsControllerMoveCollection200>(
    {
      url: `/collections/${collectionId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCollectionDto,
      signal,
    },
    options,
  );
};

export const getCollectionsControllerMoveCollectionMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof collectionsControllerMoveCollection>>,
    TError,
    { collectionId: number; data: BodyType<UpdateCollectionDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof collectionsControllerMoveCollection>>,
  TError,
  { collectionId: number; data: BodyType<UpdateCollectionDto> },
  TContext
> => {
  const mutationKey = ["collectionsControllerMoveCollection"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof collectionsControllerMoveCollection>>,
    { collectionId: number; data: BodyType<UpdateCollectionDto> }
  > = (props) => {
    const { collectionId, data } = props ?? {};

    return collectionsControllerMoveCollection(
      collectionId,
      data,
      requestOptions,
    );
  };

  return { mutationFn, ...mutationOptions };
};

export type CollectionsControllerMoveCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof collectionsControllerMoveCollection>>
>;
export type CollectionsControllerMoveCollectionMutationBody =
  BodyType<UpdateCollectionDto>;
export type CollectionsControllerMoveCollectionMutationError = ErrorType<void>;

/**
 * @summary 스크랩 보관함 이동
 */
export const useCollectionsControllerMoveCollection = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof collectionsControllerMoveCollection>>,
      TError,
      { collectionId: number; data: BodyType<UpdateCollectionDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof collectionsControllerMoveCollection>>,
  TError,
  { collectionId: number; data: BodyType<UpdateCollectionDto> },
  TContext
> => {
  return useMutation(
    getCollectionsControllerMoveCollectionMutationOptions(options),
    queryClient,
  );
};
/**
 * 스크랩을 삭제합니다. 본인 소유가 아니거나 존재하지 않으면 404 를 반환합니다.
 * (스크랩된 프로필 카드 원본은 삭제되지 않습니다.)
 * @summary 스크랩 삭제 (보관함에서 빼기)
 */
export const collectionsControllerDeleteCollection = (
  collectionId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CollectionsControllerDeleteCollection200>(
    { url: `/collections/${collectionId}`, method: "DELETE", signal },
    options,
  );
};

export const getCollectionsControllerDeleteCollectionMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>,
    TError,
    { collectionId: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>,
  TError,
  { collectionId: number },
  TContext
> => {
  const mutationKey = ["collectionsControllerDeleteCollection"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>,
    { collectionId: number }
  > = (props) => {
    const { collectionId } = props ?? {};

    return collectionsControllerDeleteCollection(collectionId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CollectionsControllerDeleteCollectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>
>;

export type CollectionsControllerDeleteCollectionMutationError =
  ErrorType<void>;

/**
 * @summary 스크랩 삭제 (보관함에서 빼기)
 */
export const useCollectionsControllerDeleteCollection = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>,
      TError,
      { collectionId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof collectionsControllerDeleteCollection>>,
  TError,
  { collectionId: number },
  TContext
> => {
  return useMutation(
    getCollectionsControllerDeleteCollectionMutationOptions(options),
    queryClient,
  );
};
