/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateProfileCardTemplateDto,
  ProfileCardTemplatesControllerCreate200,
  ProfileCardTemplatesControllerDelete200,
  ProfileCardTemplatesControllerFindAll200,
  ProfileCardTemplatesControllerFindAllParams,
  ProfileCardTemplatesControllerFindOne200,
  ProfileCardTemplatesControllerUpdate200,
  UpdateProfileCardTemplateDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * jobTypeId 를 넘기면 해당 직군의 템플릿만 조회합니다. (생략 시 전체)
 * 템플릿은 createdAt 이 없어 sort 는 id·version 만 허용하며 기본값은 id 입니다.
 * @summary 프로필 카드 템플릿 목록 조회 (public)
 */
export const profileCardTemplatesControllerFindAll = (
  params: ProfileCardTemplatesControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardTemplatesControllerFindAll200>(
    { url: `/profile-card-templates`, method: "GET", params, signal },
    options,
  );
};

export const getProfileCardTemplatesControllerFindAllQueryKey = (
  params?: ProfileCardTemplatesControllerFindAllParams,
) => {
  return [`/profile-card-templates`, ...(params ? [params] : [])] as const;
};

export const getProfileCardTemplatesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: ProfileCardTemplatesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProfileCardTemplatesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>
  > = ({ signal }) =>
    profileCardTemplatesControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileCardTemplatesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>
>;
export type ProfileCardTemplatesControllerFindAllQueryError =
  ErrorType<unknown>;

export function useProfileCardTemplatesControllerFindAll<
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: ProfileCardTemplatesControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardTemplatesControllerFindAll<
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: ProfileCardTemplatesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardTemplatesControllerFindAll<
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: ProfileCardTemplatesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 프로필 카드 템플릿 목록 조회 (public)
 */

export function useProfileCardTemplatesControllerFindAll<
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: ProfileCardTemplatesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfileCardTemplatesControllerFindAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 해당 직군의 새 활성 버전으로 발행됩니다. 기존 활성 버전은 과거 버전으로 강등됩니다.
 * @summary 프로필 카드 템플릿 발행 (ADMIN)
 */
export const profileCardTemplatesControllerCreate = (
  createProfileCardTemplateDto: BodyType<CreateProfileCardTemplateDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardTemplatesControllerCreate200>(
    {
      url: `/profile-card-templates`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createProfileCardTemplateDto,
      signal,
    },
    options,
  );
};

export const getProfileCardTemplatesControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCardTemplatesControllerCreate>>,
    TError,
    { data: BodyType<CreateProfileCardTemplateDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCardTemplatesControllerCreate>>,
  TError,
  { data: BodyType<CreateProfileCardTemplateDto> },
  TContext
> => {
  const mutationKey = ["profileCardTemplatesControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCardTemplatesControllerCreate>>,
    { data: BodyType<CreateProfileCardTemplateDto> }
  > = (props) => {
    const { data } = props ?? {};

    return profileCardTemplatesControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCardTemplatesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCardTemplatesControllerCreate>>
>;
export type ProfileCardTemplatesControllerCreateMutationBody =
  BodyType<CreateProfileCardTemplateDto>;
export type ProfileCardTemplatesControllerCreateMutationError = ErrorType<void>;

/**
 * @summary 프로필 카드 템플릿 발행 (ADMIN)
 */
export const useProfileCardTemplatesControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCardTemplatesControllerCreate>>,
      TError,
      { data: BodyType<CreateProfileCardTemplateDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCardTemplatesControllerCreate>>,
  TError,
  { data: BodyType<CreateProfileCardTemplateDto> },
  TContext
> => {
  return useMutation(
    getProfileCardTemplatesControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary 프로필 카드 템플릿 단건 조회 (public)
 */
export const profileCardTemplatesControllerFindOne = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardTemplatesControllerFindOne200>(
    { url: `/profile-card-templates/${id}`, method: "GET", signal },
    options,
  );
};

export const getProfileCardTemplatesControllerFindOneQueryKey = (
  id: number,
) => {
  return [`/profile-card-templates/${id}`] as const;
};

export const getProfileCardTemplatesControllerFindOneQueryOptions = <
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getProfileCardTemplatesControllerFindOneQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>
  > = ({ signal }) =>
    profileCardTemplatesControllerFindOne(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ProfileCardTemplatesControllerFindOneQueryResult = NonNullable<
  Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>
>;
export type ProfileCardTemplatesControllerFindOneQueryError = ErrorType<void>;

export function useProfileCardTemplatesControllerFindOne<
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardTemplatesControllerFindOne<
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
          TError,
          Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useProfileCardTemplatesControllerFindOne<
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 프로필 카드 템플릿 단건 조회 (public)
 */

export function useProfileCardTemplatesControllerFindOne<
  TData = Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
  TError = ErrorType<void>,
>(
  id: number,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof profileCardTemplatesControllerFindOne>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getProfileCardTemplatesControllerFindOneQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 활성 템플릿은 수정 불가하므로, 수정 시 version 을 증가시켜 새 활성 버전을 발행합니다.
 * 기존 버전은 불변으로 남아 이미 사용중인 카드에 영향이 없습니다.
 * @summary 프로필 카드 템플릿 수정 (ADMIN)
 */
export const profileCardTemplatesControllerUpdate = (
  id: number,
  updateProfileCardTemplateDto: BodyType<UpdateProfileCardTemplateDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardTemplatesControllerUpdate200>(
    {
      url: `/profile-card-templates/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateProfileCardTemplateDto,
      signal,
    },
    options,
  );
};

export const getProfileCardTemplatesControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCardTemplatesControllerUpdate>>,
    TError,
    { id: number; data: BodyType<UpdateProfileCardTemplateDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCardTemplatesControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateProfileCardTemplateDto> },
  TContext
> => {
  const mutationKey = ["profileCardTemplatesControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCardTemplatesControllerUpdate>>,
    { id: number; data: BodyType<UpdateProfileCardTemplateDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return profileCardTemplatesControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCardTemplatesControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCardTemplatesControllerUpdate>>
>;
export type ProfileCardTemplatesControllerUpdateMutationBody =
  BodyType<UpdateProfileCardTemplateDto>;
export type ProfileCardTemplatesControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary 프로필 카드 템플릿 수정 (ADMIN)
 */
export const useProfileCardTemplatesControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCardTemplatesControllerUpdate>>,
      TError,
      { id: number; data: BodyType<UpdateProfileCardTemplateDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCardTemplatesControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateProfileCardTemplateDto> },
  TContext
> => {
  return useMutation(
    getProfileCardTemplatesControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * 이 템플릿에 연결된 프로필 카드가 하나라도 있으면 삭제가 제한됩니다(409).
 * 사용중인 카드의 무결성을 보호하기 위함이며, 템플릿의 항목(items)은 함께 삭제됩니다.
 * @summary 프로필 카드 템플릿 삭제 (ADMIN)
 */
export const profileCardTemplatesControllerDelete = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ProfileCardTemplatesControllerDelete200>(
    { url: `/profile-card-templates/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getProfileCardTemplatesControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof profileCardTemplatesControllerDelete>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof profileCardTemplatesControllerDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["profileCardTemplatesControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof profileCardTemplatesControllerDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return profileCardTemplatesControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ProfileCardTemplatesControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof profileCardTemplatesControllerDelete>>
>;

export type ProfileCardTemplatesControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary 프로필 카드 템플릿 삭제 (ADMIN)
 */
export const useProfileCardTemplatesControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof profileCardTemplatesControllerDelete>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof profileCardTemplatesControllerDelete>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getProfileCardTemplatesControllerDeleteMutationOptions(options),
    queryClient,
  );
};
