/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreatePurposeDto,
  PurposesControllerCreate200,
  PurposesControllerDelete200,
  PurposesControllerFindAll200,
  PurposesControllerFindAllParams,
  PurposesControllerUpdate200,
  UpdatePurposeDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * purpose 는 createdAt 이 없어 sort 는 id·name 만 허용하며 기본값은 name 입니다.
 * @summary 모든 purposes 를 조회합니다.
 */
export const purposesControllerFindAll = (
  params: PurposesControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PurposesControllerFindAll200>(
    { url: `/purposes`, method: "GET", params, signal },
    options,
  );
};

export const getPurposesControllerFindAllQueryKey = (
  params?: PurposesControllerFindAllParams,
) => {
  return [`/purposes`, ...(params ? [params] : [])] as const;
};

export const getPurposesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof purposesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PurposesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof purposesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getPurposesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof purposesControllerFindAll>>
  > = ({ signal }) => purposesControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof purposesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PurposesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof purposesControllerFindAll>>
>;
export type PurposesControllerFindAllQueryError = ErrorType<unknown>;

export function usePurposesControllerFindAll<
  TData = Awaited<ReturnType<typeof purposesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PurposesControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof purposesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof purposesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof purposesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePurposesControllerFindAll<
  TData = Awaited<ReturnType<typeof purposesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PurposesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof purposesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof purposesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof purposesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function usePurposesControllerFindAll<
  TData = Awaited<ReturnType<typeof purposesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PurposesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof purposesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 모든 purposes 를 조회합니다.
 */

export function usePurposesControllerFindAll<
  TData = Awaited<ReturnType<typeof purposesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: PurposesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof purposesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getPurposesControllerFindAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary purposes 생성 (ADMIN)
 */
export const purposesControllerCreate = (
  createPurposeDto: BodyType<CreatePurposeDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PurposesControllerCreate200>(
    {
      url: `/purposes`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createPurposeDto,
      signal,
    },
    options,
  );
};

export const getPurposesControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purposesControllerCreate>>,
    TError,
    { data: BodyType<CreatePurposeDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof purposesControllerCreate>>,
  TError,
  { data: BodyType<CreatePurposeDto> },
  TContext
> => {
  const mutationKey = ["purposesControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purposesControllerCreate>>,
    { data: BodyType<CreatePurposeDto> }
  > = (props) => {
    const { data } = props ?? {};

    return purposesControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PurposesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof purposesControllerCreate>>
>;
export type PurposesControllerCreateMutationBody = BodyType<CreatePurposeDto>;
export type PurposesControllerCreateMutationError = ErrorType<void>;

/**
 * @summary purposes 생성 (ADMIN)
 */
export const usePurposesControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof purposesControllerCreate>>,
      TError,
      { data: BodyType<CreatePurposeDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof purposesControllerCreate>>,
  TError,
  { data: BodyType<CreatePurposeDto> },
  TContext
> => {
  return useMutation(
    getPurposesControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary purposes 수정 (ADMIN)
 */
export const purposesControllerUpdate = (
  id: string,
  updatePurposeDto: BodyType<UpdatePurposeDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PurposesControllerUpdate200>(
    {
      url: `/purposes/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updatePurposeDto,
      signal,
    },
    options,
  );
};

export const getPurposesControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purposesControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdatePurposeDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof purposesControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdatePurposeDto> },
  TContext
> => {
  const mutationKey = ["purposesControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purposesControllerUpdate>>,
    { id: string; data: BodyType<UpdatePurposeDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return purposesControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PurposesControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof purposesControllerUpdate>>
>;
export type PurposesControllerUpdateMutationBody = BodyType<UpdatePurposeDto>;
export type PurposesControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary purposes 수정 (ADMIN)
 */
export const usePurposesControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof purposesControllerUpdate>>,
      TError,
      { id: string; data: BodyType<UpdatePurposeDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof purposesControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdatePurposeDto> },
  TContext
> => {
  return useMutation(
    getPurposesControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary purposes 삭제 (ADMIN)
 */
export const purposesControllerDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<PurposesControllerDelete200>(
    { url: `/purposes/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getPurposesControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof purposesControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof purposesControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["purposesControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof purposesControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return purposesControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PurposesControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof purposesControllerDelete>>
>;

export type PurposesControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary purposes 삭제 (ADMIN)
 */
export const usePurposesControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof purposesControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof purposesControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getPurposesControllerDeleteMutationOptions(options),
    queryClient,
  );
};
