/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  AuthControllerGetGoogleLoginUrl200,
  AuthControllerGetKakaoLoginUrl200,
  AuthControllerGetNaverLoginUrl200,
  AuthControllerLogin200,
  AuthControllerLogout200,
  AuthControllerRefresh200,
  LoginDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 소셜 로그인용 Url 을 요청합니다. deviceId 가 없다면 uuid 형식으로 세팅합니다.
 *
 * **redirect_uri 는 요청의 Origin 헤더 + 서버 고정 경로로 만들어집니다.**
 * - 즉 이 요청을 보낸 프론트의 origin 으로 구글이 콜백합니다.
 *   (예: Origin `https://app.example.com` → `https://app.example.com{GOOGLE_REDIRECT_PATH}`)
 * - 브라우저 fetch 로 호출하면 Origin 이 자동으로 붙습니다. Origin 이 없으면 기본값으로 fallback 됩니다.
 * - 해당 `origin + path` 가 **구글 콘솔의 승인된 리디렉션 URI 에 등록**돼 있어야 합니다. 없으면 로그인 시 redirect_uri_mismatch 로 실패합니다.
 * - origin 은 state 와 함께 저장되어, 로그인(code 교환) 시 동일한 값으로 사용됩니다.
 * @summary 구글 소셜로그인 Url
 */
export const authControllerGetGoogleLoginUrl = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthControllerGetGoogleLoginUrl200>(
    { url: `/auth/google`, method: "GET", signal },
    options,
  );
};

export const getAuthControllerGetGoogleLoginUrlQueryKey = () => {
  return [`/auth/google`] as const;
};

export const getAuthControllerGetGoogleLoginUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetGoogleLoginUrlQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>
  > = ({ signal }) => authControllerGetGoogleLoginUrl(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGetGoogleLoginUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>
>;
export type AuthControllerGetGoogleLoginUrlQueryError = ErrorType<void>;

export function useAuthControllerGetGoogleLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetGoogleLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetGoogleLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 구글 소셜로그인 Url
 */

export function useAuthControllerGetGoogleLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetGoogleLoginUrl>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthControllerGetGoogleLoginUrlQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 네이버 로그인용 Url 을 요청합니다. redirect_uri 규칙은 구글과 동일합니다.
 *
 * **redirect_uri 는 요청의 Origin 헤더 + 서버 고정 경로(NAVER_REDIRECT_PATH)로 만들어집니다.**
 * - 해당 `origin + path` 가 **네이버 개발자센터의 Callback URL 에 등록**돼 있어야 합니다.
 * - origin 은 state 와 함께 저장되어, 로그인(code 교환) 시 동일한 값으로 사용됩니다.
 * @summary 네이버 소셜로그인 Url
 */
export const authControllerGetNaverLoginUrl = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthControllerGetNaverLoginUrl200>(
    { url: `/auth/naver`, method: "GET", signal },
    options,
  );
};

export const getAuthControllerGetNaverLoginUrlQueryKey = () => {
  return [`/auth/naver`] as const;
};

export const getAuthControllerGetNaverLoginUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetNaverLoginUrlQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>
  > = ({ signal }) => authControllerGetNaverLoginUrl(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGetNaverLoginUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>
>;
export type AuthControllerGetNaverLoginUrlQueryError = ErrorType<void>;

export function useAuthControllerGetNaverLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetNaverLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetNaverLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 네이버 소셜로그인 Url
 */

export function useAuthControllerGetNaverLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetNaverLoginUrl>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthControllerGetNaverLoginUrlQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 카카오 로그인용 Url 을 요청합니다. redirect_uri 규칙은 구글/네이버와 동일합니다.
 *
 * **redirect_uri 는 요청의 Origin 헤더 + 서버 고정 경로(KAKAO_REDIRECT_PATH)로 만들어집니다.**
 * - 해당 `origin + path` 가 **카카오 개발자 콘솔의 Redirect URI 에 등록**돼 있어야 합니다.
 * - origin 은 state 와 함께 저장되어, 로그인(code 교환) 시 동일한 값으로 사용됩니다.
 * @summary 카카오 소셜로그인 Url
 */
export const authControllerGetKakaoLoginUrl = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthControllerGetKakaoLoginUrl200>(
    { url: `/auth/kakao`, method: "GET", signal },
    options,
  );
};

export const getAuthControllerGetKakaoLoginUrlQueryKey = () => {
  return [`/auth/kakao`] as const;
};

export const getAuthControllerGetKakaoLoginUrlQueryOptions = <
  TData = Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getAuthControllerGetKakaoLoginUrlQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>
  > = ({ signal }) => authControllerGetKakaoLoginUrl(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type AuthControllerGetKakaoLoginUrlQueryResult = NonNullable<
  Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>
>;
export type AuthControllerGetKakaoLoginUrlQueryError = ErrorType<void>;

export function useAuthControllerGetKakaoLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetKakaoLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
          TError,
          Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useAuthControllerGetKakaoLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 카카오 소셜로그인 Url
 */

export function useAuthControllerGetKakaoLoginUrl<
  TData = Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof authControllerGetKakaoLoginUrl>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getAuthControllerGetKakaoLoginUrlQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 쿠키에 device_id 를 uuid 형식으로 가지고 있어야 합니다.
 *
 * 이는 GET /auth/{provider} 요청 시 자동 설정되니 신경쓰지 않아도 됨.
 *
 * body 에 provider 는 .toUpperCase 해서 보내주세요! (대문자로) (GOOGLE, KAKAO, NAVER)
 *
 * **Response cookie 값**
 * - refresh_token (httpOnly)
 *
 * **JWT payload 구조**
 * - accessToken: `{ sub: 유저 id, role: 역할(0=USER, 1=ADMIN) }`
 *   - role 은 권한 가드의 앞단 컷 최적화용이며, 최종 권위는 DB 의 user.role 입니다.
 * - refreshToken: `{ sub: 유저 id }` (role 미포함)
 *   - refresh 시 DB 에서 현재 role 을 다시 조회해 accessToken 에 반영하므로 refresh 에는 role 을 넣지 않습니다.
 * @summary 회원가입 및 로그인
 */
export const authControllerLogin = (
  loginDto: BodyType<LoginDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthControllerLogin200>(
    {
      url: `/auth/login`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: loginDto,
      signal,
    },
    options,
  );
};

export const getAuthControllerLoginMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogin>>,
    TError,
    { data: BodyType<LoginDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: BodyType<LoginDto> },
  TContext
> => {
  const mutationKey = ["authControllerLogin"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogin>>,
    { data: BodyType<LoginDto> }
  > = (props) => {
    const { data } = props ?? {};

    return authControllerLogin(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLoginMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogin>>
>;
export type AuthControllerLoginMutationBody = BodyType<LoginDto>;
export type AuthControllerLoginMutationError = ErrorType<void>;

/**
 * @summary 회원가입 및 로그인
 */
export const useAuthControllerLogin = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogin>>,
      TError,
      { data: BodyType<LoginDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogin>>,
  TError,
  { data: BodyType<LoginDto> },
  TContext
> => {
  return useMutation(
    getAuthControllerLoginMutationOptions(options),
    queryClient,
  );
};
/**
 * 인증 토큰 (accessToken, refreshToken) 을 갱신합니다.
 *
 * **Request cookie 값**
 * - device_id
 * - refresh_token
 *
 * 결과: device_id, refresh_token 갱신, accessToken 응답
 * @summary 토큰 refresh
 */
export const authControllerRefresh = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthControllerRefresh200>(
    { url: `/auth/refresh`, method: "POST", signal },
    options,
  );
};

export const getAuthControllerRefreshMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerRefresh>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerRefresh"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerRefresh>>,
    void
  > = () => {
    return authControllerRefresh(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerRefreshMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerRefresh>>
>;

export type AuthControllerRefreshMutationError = ErrorType<void>;

/**
 * @summary 토큰 refresh
 */
export const useAuthControllerRefresh = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerRefresh>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerRefresh>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerRefreshMutationOptions(options),
    queryClient,
  );
};
/**
 * 로그아웃 (인증 비활성화) 합니다.
 *
 * **Request cookie 값**
 * - device_id
 * - refresh_token
 *
 * **결과**
 * - 쿠키에서 refresh_token 제거 및 DB 에서 비활성화
 * @summary 로그아웃
 */
export const authControllerLogout = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<AuthControllerLogout200>(
    { url: `/auth/logout`, method: "POST", signal },
    options,
  );
};

export const getAuthControllerLogoutMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof authControllerLogout>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof authControllerLogout>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = ["authControllerLogout"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof authControllerLogout>>,
    void
  > = () => {
    return authControllerLogout(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AuthControllerLogoutMutationResult = NonNullable<
  Awaited<ReturnType<typeof authControllerLogout>>
>;

export type AuthControllerLogoutMutationError = ErrorType<void>;

/**
 * @summary 로그아웃
 */
export const useAuthControllerLogout = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof authControllerLogout>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof authControllerLogout>>,
  TError,
  void,
  TContext
> => {
  return useMutation(
    getAuthControllerLogoutMutationOptions(options),
    queryClient,
  );
};
