/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  NotificationsControllerCheckRead200,
  NotificationsControllerFindAll200,
  NotificationsControllerFindAllParams,
  NotificationsControllerStream200,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 로그인한 사용자의 실시간 알림을 SSE(Server-Sent Events)로 구독합니다.
 *
 * 연결 요청이 수락되거나 거절되면 `notification` 이벤트로 알림이 전달됩니다.
 *
 * **이벤트 종류**
 *
 * - notification: 새 알림. data에는 알림 JSON 문자열이 포함됩니다.
 *
 * - ping: 연결 유지를 위해 20초마다 전달되는 heartbeat입니다.
 *
 * 스트림은 인증 상태를 다시 확인할 수 있도록 최대 30분 동안 유지되며,
 *
 * 종료된 이후에는 새로운 액세스 토큰으로 다시 연결해야 합니다.
 *
 * 실시간 연결 중이 아니었던 기간의 알림은 알림 목록 조회 API로 확인할 수 있습니다.
 * @summary 실시간 알림 스트림 구독
 */
export const notificationsControllerStream = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<NotificationsControllerStream200>(
    { url: `/notifications/stream`, method: "GET", signal },
    options,
  );
};

export const getNotificationsControllerStreamQueryKey = () => {
  return [`/notifications/stream`] as const;
};

export const getNotificationsControllerStreamQueryOptions = <
  TData = Awaited<ReturnType<typeof notificationsControllerStream>>,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof notificationsControllerStream>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getNotificationsControllerStreamQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof notificationsControllerStream>>
  > = ({ signal }) => notificationsControllerStream(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof notificationsControllerStream>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NotificationsControllerStreamQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificationsControllerStream>>
>;
export type NotificationsControllerStreamQueryError = ErrorType<void>;

export function useNotificationsControllerStream<
  TData = Awaited<ReturnType<typeof notificationsControllerStream>>,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerStream>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsControllerStream>>,
          TError,
          Awaited<ReturnType<typeof notificationsControllerStream>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNotificationsControllerStream<
  TData = Awaited<ReturnType<typeof notificationsControllerStream>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerStream>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsControllerStream>>,
          TError,
          Awaited<ReturnType<typeof notificationsControllerStream>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNotificationsControllerStream<
  TData = Awaited<ReturnType<typeof notificationsControllerStream>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerStream>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 실시간 알림 스트림 구독
 */

export function useNotificationsControllerStream<
  TData = Awaited<ReturnType<typeof notificationsControllerStream>>,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerStream>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getNotificationsControllerStreamQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 로그인한 사용자에게 생성된 알림을 최신순으로 페이지네이션 조회합니다.
 *
 * 앱이 꺼져 있거나 SSE에 연결되지 않았던 동안 생성된 알림도 포함됩니다.
 *
 * **요청 query**
 *
 * - page: 페이지 번호 (기본값 1)
 *
 * - limit: 페이지당 항목 수 (기본값 10, 최대 100)
 *
 * - sort: 정렬 기준. `createdAt`만 허용됩니다.
 *
 * - order: 정렬 방향 (`asc` 또는 `desc`, 기본값 `desc`)
 *
 * - isRead: 읽음 여부 필터 (`true` 또는 `false`, optional)
 *
 * **응답 body**
 *
 * - items: 알림 목록
 *
 * - items[].type: 알림 타입 (1 수락 / 2 거절)
 *
 * - items[].payload: 연결 요청 및 상대 카드 정보
 *
 * - items[].readAt: 읽은 시각. 미읽음이면 null
 *
 * - items[].createdAt: 알림 생성 시각
 *
 * - metadata: 페이지네이션 정보
 * @summary 내 알림 목록 조회
 */
export const notificationsControllerFindAll = (
  params: NotificationsControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<NotificationsControllerFindAll200>(
    { url: `/notifications`, method: "GET", params, signal },
    options,
  );
};

export const getNotificationsControllerFindAllQueryKey = (
  params?: NotificationsControllerFindAllParams,
) => {
  return [`/notifications`, ...(params ? [params] : [])] as const;
};

export const getNotificationsControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>,
  TError = ErrorType<void>,
>(
  params: NotificationsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getNotificationsControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof notificationsControllerFindAll>>
  > = ({ signal }) =>
    notificationsControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof notificationsControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type NotificationsControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof notificationsControllerFindAll>>
>;
export type NotificationsControllerFindAllQueryError = ErrorType<void>;

export function useNotificationsControllerFindAll<
  TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>,
  TError = ErrorType<void>,
>(
  params: NotificationsControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof notificationsControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNotificationsControllerFindAll<
  TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>,
  TError = ErrorType<void>,
>(
  params: NotificationsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof notificationsControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof notificationsControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useNotificationsControllerFindAll<
  TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>,
  TError = ErrorType<void>,
>(
  params: NotificationsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 알림 목록 조회
 */

export function useNotificationsControllerFindAll<
  TData = Awaited<ReturnType<typeof notificationsControllerFindAll>>,
  TError = ErrorType<void>,
>(
  params: NotificationsControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof notificationsControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getNotificationsControllerFindAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 로그인한 사용자가 소유한 알림을 읽음 상태로 변경합니다.
 *
 * 이미 읽은 알림에 다시 요청해도 읽음 상태가 유지됩니다.
 *
 * 다른 사용자의 알림이거나 존재하지 않는 알림이면 찾을 수 없는 알림으로 처리합니다.
 *
 * **path param**
 *
 * - id: 읽음 처리할 알림 ID
 *
 * **응답 body**
 *
 * - 없음
 * @summary 알림 읽음 처리
 */
export const notificationsControllerCheckRead = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<NotificationsControllerCheckRead200>(
    { url: `/notifications/${id}/read`, method: "PATCH", signal },
    options,
  );
};

export const getNotificationsControllerCheckReadMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof notificationsControllerCheckRead>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof notificationsControllerCheckRead>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["notificationsControllerCheckRead"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof notificationsControllerCheckRead>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return notificationsControllerCheckRead(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type NotificationsControllerCheckReadMutationResult = NonNullable<
  Awaited<ReturnType<typeof notificationsControllerCheckRead>>
>;

export type NotificationsControllerCheckReadMutationError = ErrorType<void>;

/**
 * @summary 알림 읽음 처리
 */
export const useNotificationsControllerCheckRead = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof notificationsControllerCheckRead>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof notificationsControllerCheckRead>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getNotificationsControllerCheckReadMutationOptions(options),
    queryClient,
  );
};
