/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  ConnectionsControllerGetConnection200,
  ConnectionsControllerGetMyConnections200,
  ConnectionsControllerGetMyConnectionsParams,
  ConnectionsControllerRemoveConnection200,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 연결 요청이 수락되어 성립된 연결(보관)을 페이지네이션으로 조회합니다.
 * 내가 요청자든 수신자든 당사자인 연결이 모두 포함되며,
 * 내 관점에서 제거(소프트 삭제)한 연결은 제외됩니다.
 *
 * **요청 query**
 * - page, limit, sort, order: 페이지네이션 옵션
 *
 * **응답 body**
 * - items: 연결 목록. 각 항목의 card 는 성립 시점의 상대 카드 스냅샷
 * - metadata: 페이지네이션 정보
 * @summary 내 보관함(성립된 연결) 목록 조회
 */
export const connectionsControllerGetMyConnections = (
  params: ConnectionsControllerGetMyConnectionsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionsControllerGetMyConnections200>(
    { url: `/connections`, method: "GET", params, signal },
    options,
  );
};

export const getConnectionsControllerGetMyConnectionsQueryKey = (
  params?: ConnectionsControllerGetMyConnectionsParams,
) => {
  return [`/connections`, ...(params ? [params] : [])] as const;
};

export const getConnectionsControllerGetMyConnectionsQueryOptions = <
  TData = Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
  TError = ErrorType<void>,
>(
  params: ConnectionsControllerGetMyConnectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getConnectionsControllerGetMyConnectionsQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>
  > = ({ signal }) =>
    connectionsControllerGetMyConnections(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ConnectionsControllerGetMyConnectionsQueryResult = NonNullable<
  Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>
>;
export type ConnectionsControllerGetMyConnectionsQueryError = ErrorType<void>;

export function useConnectionsControllerGetMyConnections<
  TData = Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
  TError = ErrorType<void>,
>(
  params: ConnectionsControllerGetMyConnectionsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
          TError,
          Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useConnectionsControllerGetMyConnections<
  TData = Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
  TError = ErrorType<void>,
>(
  params: ConnectionsControllerGetMyConnectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
          TError,
          Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useConnectionsControllerGetMyConnections<
  TData = Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
  TError = ErrorType<void>,
>(
  params: ConnectionsControllerGetMyConnectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 보관함(성립된 연결) 목록 조회
 */

export function useConnectionsControllerGetMyConnections<
  TData = Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
  TError = ErrorType<void>,
>(
  params: ConnectionsControllerGetMyConnectionsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetMyConnections>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getConnectionsControllerGetMyConnectionsQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 성립된 연결(보관) 하나를 조회합니다.
 * 존재하지 않거나 내가 당사자가 아니거나 이미 제거한 연결이면 404 를 반환합니다.
 *
 * **path param**
 * - id: 연결(보관) ID
 *
 * **응답 body**
 * - id: 연결(보관) ID
 * - card: 성립 시점의 상대 카드 스냅샷
 * - message: 연결 요청 시 첨부한 메시지
 * - connectedAt: 연결 성립 시각
 * @summary 내 보관함의 연결 단건 조회
 */
export const connectionsControllerGetConnection = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionsControllerGetConnection200>(
    { url: `/connections/${id}`, method: "GET", signal },
    options,
  );
};

export const getConnectionsControllerGetConnectionQueryKey = (id: string) => {
  return [`/connections/${id}`] as const;
};

export const getConnectionsControllerGetConnectionQueryOptions = <
  TData = Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getConnectionsControllerGetConnectionQueryKey(id);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof connectionsControllerGetConnection>>
  > = ({ signal }) =>
    connectionsControllerGetConnection(id, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ConnectionsControllerGetConnectionQueryResult = NonNullable<
  Awaited<ReturnType<typeof connectionsControllerGetConnection>>
>;
export type ConnectionsControllerGetConnectionQueryError = ErrorType<void>;

export function useConnectionsControllerGetConnection<
  TData = Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
  TError = ErrorType<void>,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
          TError,
          Awaited<ReturnType<typeof connectionsControllerGetConnection>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useConnectionsControllerGetConnection<
  TData = Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
          TError,
          Awaited<ReturnType<typeof connectionsControllerGetConnection>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useConnectionsControllerGetConnection<
  TData = Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 내 보관함의 연결 단건 조회
 */

export function useConnectionsControllerGetConnection<
  TData = Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
  TError = ErrorType<void>,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof connectionsControllerGetConnection>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getConnectionsControllerGetConnectionQueryOptions(
    id,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 성립된 연결을 내 보관함에서 제거합니다(내 관점 소프트 삭제).
 * 상대방 보관함에는 그대로 남습니다.
 * 존재하지 않거나 내가 당사자가 아니거나 이미 제거한 연결이면 404 를 반환합니다.
 *
 * **path param**
 * - id: 연결(보관) ID
 *
 * **응답 body**
 * - 없음
 * @summary 보관함에서 연결 제거
 */
export const connectionsControllerRemoveConnection = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<ConnectionsControllerRemoveConnection200>(
    { url: `/connections/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getConnectionsControllerRemoveConnectionMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof connectionsControllerRemoveConnection>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof connectionsControllerRemoveConnection>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["connectionsControllerRemoveConnection"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof connectionsControllerRemoveConnection>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return connectionsControllerRemoveConnection(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConnectionsControllerRemoveConnectionMutationResult = NonNullable<
  Awaited<ReturnType<typeof connectionsControllerRemoveConnection>>
>;

export type ConnectionsControllerRemoveConnectionMutationError =
  ErrorType<void>;

/**
 * @summary 보관함에서 연결 제거
 */
export const useConnectionsControllerRemoveConnection = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof connectionsControllerRemoveConnection>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof connectionsControllerRemoveConnection>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getConnectionsControllerRemoveConnectionMutationOptions(options),
    queryClient,
  );
};
