/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CollectionGroupsControllerCreateCollectionGroup200,
  CollectionGroupsControllerDeleteCollectionGroup200,
  CollectionGroupsControllerGetCollectionGroups200,
  CollectionGroupsControllerGetCollectionItems200,
  CollectionGroupsControllerGetCollectionItemsParams,
  CollectionGroupsControllerUpdateCollectionGroup200,
  CreateCollectionGroupDto,
  UpdateCollectionGroupDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 로그인한 유저의 새 보관함을 생성합니다. 이름은 유저별로 유일하며,
 * 중복되면 409 를 반환합니다.
 * @summary 보관함(그룹) 생성
 */
export const collectionGroupsControllerCreateCollectionGroup = (
  createCollectionGroupDto: BodyType<CreateCollectionGroupDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CollectionGroupsControllerCreateCollectionGroup200>(
    {
      url: `/collection-groups`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCollectionGroupDto,
      signal,
    },
    options,
  );
};

export const getCollectionGroupsControllerCreateCollectionGroupMutationOptions =
  <TError = ErrorType<void>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof collectionGroupsControllerCreateCollectionGroup>
      >,
      TError,
      { data: BodyType<CreateCollectionGroupDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<ReturnType<typeof collectionGroupsControllerCreateCollectionGroup>>,
    TError,
    { data: BodyType<CreateCollectionGroupDto> },
    TContext
  > => {
    const mutationKey = ["collectionGroupsControllerCreateCollectionGroup"];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof collectionGroupsControllerCreateCollectionGroup>
      >,
      { data: BodyType<CreateCollectionGroupDto> }
    > = (props) => {
      const { data } = props ?? {};

      return collectionGroupsControllerCreateCollectionGroup(
        data,
        requestOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type CollectionGroupsControllerCreateCollectionGroupMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof collectionGroupsControllerCreateCollectionGroup>>
  >;
export type CollectionGroupsControllerCreateCollectionGroupMutationBody =
  BodyType<CreateCollectionGroupDto>;
export type CollectionGroupsControllerCreateCollectionGroupMutationError =
  ErrorType<void>;

/**
 * @summary 보관함(그룹) 생성
 */
export const useCollectionGroupsControllerCreateCollectionGroup = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof collectionGroupsControllerCreateCollectionGroup>
      >,
      TError,
      { data: BodyType<CreateCollectionGroupDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof collectionGroupsControllerCreateCollectionGroup>>,
  TError,
  { data: BodyType<CreateCollectionGroupDto> },
  TContext
> => {
  return useMutation(
    getCollectionGroupsControllerCreateCollectionGroupMutationOptions(options),
    queryClient,
  );
};
/**
 * 로그인한 유저의 보관함 목록을 반환합니다. 각 보관함에는 담긴 스크랩 수(itemCount)가 포함됩니다.
 * 보관함 내부의 카드 목록은 `GET /collection-groups/{groupId}/items` 로 조회하세요.
 * @summary 보관함(그룹) 목록 조회
 */
export const collectionGroupsControllerGetCollectionGroups = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CollectionGroupsControllerGetCollectionGroups200>(
    { url: `/collection-groups`, method: "GET", signal },
    options,
  );
};

export const getCollectionGroupsControllerGetCollectionGroupsQueryKey = () => {
  return [`/collection-groups`] as const;
};

export const getCollectionGroupsControllerGetCollectionGroupsQueryOptions = <
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
  >,
  TError = ErrorType<void>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof collectionGroupsControllerGetCollectionGroups>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCollectionGroupsControllerGetCollectionGroupsQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof collectionGroupsControllerGetCollectionGroups>>
  > = ({ signal }) =>
    collectionGroupsControllerGetCollectionGroups(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof collectionGroupsControllerGetCollectionGroups>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CollectionGroupsControllerGetCollectionGroupsQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof collectionGroupsControllerGetCollectionGroups>>
  >;
export type CollectionGroupsControllerGetCollectionGroupsQueryError =
  ErrorType<void>;

export function useCollectionGroupsControllerGetCollectionGroups<
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
  >,
  TError = ErrorType<void>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
          >,
          TError,
          Awaited<
            ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCollectionGroupsControllerGetCollectionGroups<
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
  >,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
          >,
          TError,
          Awaited<
            ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCollectionGroupsControllerGetCollectionGroups<
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
  >,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 보관함(그룹) 목록 조회
 */

export function useCollectionGroupsControllerGetCollectionGroups<
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
  >,
  TError = ErrorType<void>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionGroups>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCollectionGroupsControllerGetCollectionGroupsQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 특정 보관함에 담긴 스크랩(프로필 카드) 목록을 페이지네이션으로 조회합니다.
 * 본인 소유 보관함이 아니거나 존재하지 않으면 404 를 반환합니다.
 *
 * ★ 각 카드는 단건 조회와 동일한 완전한 형태이며, createdAt 컬럼이 없어 저장(삽입) 순서로 정렬됩니다.
 * @summary 보관함 내 스크랩 목록 조회
 */
export const collectionGroupsControllerGetCollectionItems = (
  groupId: number,
  params: CollectionGroupsControllerGetCollectionItemsParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CollectionGroupsControllerGetCollectionItems200>(
    {
      url: `/collection-groups/${groupId}/items`,
      method: "GET",
      params,
      signal,
    },
    options,
  );
};

export const getCollectionGroupsControllerGetCollectionItemsQueryKey = (
  groupId: number,
  params?: CollectionGroupsControllerGetCollectionItemsParams,
) => {
  return [
    `/collection-groups/${groupId}/items`,
    ...(params ? [params] : []),
  ] as const;
};

export const getCollectionGroupsControllerGetCollectionItemsQueryOptions = <
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionItems>
  >,
  TError = ErrorType<void>,
>(
  groupId: number,
  params: CollectionGroupsControllerGetCollectionItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionItems>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCollectionGroupsControllerGetCollectionItemsQueryKey(groupId, params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof collectionGroupsControllerGetCollectionItems>>
  > = ({ signal }) =>
    collectionGroupsControllerGetCollectionItems(
      groupId,
      params,
      requestOptions,
      signal,
    );

  return {
    queryKey,
    queryFn,
    enabled: groupId !== null && groupId !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof collectionGroupsControllerGetCollectionItems>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CollectionGroupsControllerGetCollectionItemsQueryResult =
  NonNullable<
    Awaited<ReturnType<typeof collectionGroupsControllerGetCollectionItems>>
  >;
export type CollectionGroupsControllerGetCollectionItemsQueryError =
  ErrorType<void>;

export function useCollectionGroupsControllerGetCollectionItems<
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionItems>
  >,
  TError = ErrorType<void>,
>(
  groupId: number,
  params: CollectionGroupsControllerGetCollectionItemsParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionItems>
        >,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof collectionGroupsControllerGetCollectionItems>
          >,
          TError,
          Awaited<
            ReturnType<typeof collectionGroupsControllerGetCollectionItems>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCollectionGroupsControllerGetCollectionItems<
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionItems>
  >,
  TError = ErrorType<void>,
>(
  groupId: number,
  params: CollectionGroupsControllerGetCollectionItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionItems>
        >,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<
            ReturnType<typeof collectionGroupsControllerGetCollectionItems>
          >,
          TError,
          Awaited<
            ReturnType<typeof collectionGroupsControllerGetCollectionItems>
          >
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCollectionGroupsControllerGetCollectionItems<
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionItems>
  >,
  TError = ErrorType<void>,
>(
  groupId: number,
  params: CollectionGroupsControllerGetCollectionItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionItems>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 보관함 내 스크랩 목록 조회
 */

export function useCollectionGroupsControllerGetCollectionItems<
  TData = Awaited<
    ReturnType<typeof collectionGroupsControllerGetCollectionItems>
  >,
  TError = ErrorType<void>,
>(
  groupId: number,
  params: CollectionGroupsControllerGetCollectionItemsParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<
          ReturnType<typeof collectionGroupsControllerGetCollectionItems>
        >,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions =
    getCollectionGroupsControllerGetCollectionItemsQueryOptions(
      groupId,
      params,
      options,
    );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 보관함 이름을 변경합니다. 본인 소유가 아니거나 존재하지 않으면 404,
 * 변경할 이름이 이미 존재하면 409 를 반환합니다.
 * @summary 보관함(그룹) 이름 수정
 */
export const collectionGroupsControllerUpdateCollectionGroup = (
  groupId: number,
  updateCollectionGroupDto: BodyType<UpdateCollectionGroupDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CollectionGroupsControllerUpdateCollectionGroup200>(
    {
      url: `/collection-groups/${groupId}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateCollectionGroupDto,
      signal,
    },
    options,
  );
};

export const getCollectionGroupsControllerUpdateCollectionGroupMutationOptions =
  <TError = ErrorType<void>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof collectionGroupsControllerUpdateCollectionGroup>
      >,
      TError,
      { groupId: number; data: BodyType<UpdateCollectionGroupDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<ReturnType<typeof collectionGroupsControllerUpdateCollectionGroup>>,
    TError,
    { groupId: number; data: BodyType<UpdateCollectionGroupDto> },
    TContext
  > => {
    const mutationKey = ["collectionGroupsControllerUpdateCollectionGroup"];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof collectionGroupsControllerUpdateCollectionGroup>
      >,
      { groupId: number; data: BodyType<UpdateCollectionGroupDto> }
    > = (props) => {
      const { groupId, data } = props ?? {};

      return collectionGroupsControllerUpdateCollectionGroup(
        groupId,
        data,
        requestOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type CollectionGroupsControllerUpdateCollectionGroupMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof collectionGroupsControllerUpdateCollectionGroup>>
  >;
export type CollectionGroupsControllerUpdateCollectionGroupMutationBody =
  BodyType<UpdateCollectionGroupDto>;
export type CollectionGroupsControllerUpdateCollectionGroupMutationError =
  ErrorType<void>;

/**
 * @summary 보관함(그룹) 이름 수정
 */
export const useCollectionGroupsControllerUpdateCollectionGroup = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof collectionGroupsControllerUpdateCollectionGroup>
      >,
      TError,
      { groupId: number; data: BodyType<UpdateCollectionGroupDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof collectionGroupsControllerUpdateCollectionGroup>>,
  TError,
  { groupId: number; data: BodyType<UpdateCollectionGroupDto> },
  TContext
> => {
  return useMutation(
    getCollectionGroupsControllerUpdateCollectionGroupMutationOptions(options),
    queryClient,
  );
};
/**
 * 보관함을 삭제합니다. 본인 소유가 아니거나 존재하지 않으면 404 를 반환합니다.
 *
 * ★ 보관함에 담긴 스크랩은 함께 삭제됩니다(스크랩된 프로필 카드 원본은 삭제되지 않습니다).
 * @summary 보관함(그룹) 삭제
 */
export const collectionGroupsControllerDeleteCollectionGroup = (
  groupId: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CollectionGroupsControllerDeleteCollectionGroup200>(
    { url: `/collection-groups/${groupId}`, method: "DELETE", signal },
    options,
  );
};

export const getCollectionGroupsControllerDeleteCollectionGroupMutationOptions =
  <TError = ErrorType<void>, TContext = unknown>(options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof collectionGroupsControllerDeleteCollectionGroup>
      >,
      TError,
      { groupId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  }): UseMutationOptions<
    Awaited<ReturnType<typeof collectionGroupsControllerDeleteCollectionGroup>>,
    TError,
    { groupId: number },
    TContext
  > => {
    const mutationKey = ["collectionGroupsControllerDeleteCollectionGroup"];
    const { mutation: mutationOptions, request: requestOptions } = options
      ? options.mutation &&
        "mutationKey" in options.mutation &&
        options.mutation.mutationKey
        ? options
        : { ...options, mutation: { ...options.mutation, mutationKey } }
      : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
      Awaited<
        ReturnType<typeof collectionGroupsControllerDeleteCollectionGroup>
      >,
      { groupId: number }
    > = (props) => {
      const { groupId } = props ?? {};

      return collectionGroupsControllerDeleteCollectionGroup(
        groupId,
        requestOptions,
      );
    };

    return { mutationFn, ...mutationOptions };
  };

export type CollectionGroupsControllerDeleteCollectionGroupMutationResult =
  NonNullable<
    Awaited<ReturnType<typeof collectionGroupsControllerDeleteCollectionGroup>>
  >;

export type CollectionGroupsControllerDeleteCollectionGroupMutationError =
  ErrorType<void>;

/**
 * @summary 보관함(그룹) 삭제
 */
export const useCollectionGroupsControllerDeleteCollectionGroup = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<
        ReturnType<typeof collectionGroupsControllerDeleteCollectionGroup>
      >,
      TError,
      { groupId: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof collectionGroupsControllerDeleteCollectionGroup>>,
  TError,
  { groupId: number },
  TContext
> => {
  return useMutation(
    getCollectionGroupsControllerDeleteCollectionGroupMutationOptions(options),
    queryClient,
  );
};
