/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.2.2
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateSkillCategoryDto,
  SkillCategoriesControllerCreate200,
  SkillCategoriesControllerFindAll200,
  SkillCategoriesControllerRemove200,
  SkillCategoriesControllerUpdate200,
  UpdateSkillCategoryDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * @summary 스킬 카테고리 전체 조회
 */
export const skillCategoriesControllerFindAll = (
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SkillCategoriesControllerFindAll200>(
    { url: `/skill-categories`, method: "GET", signal },
    options,
  );
};

export const getSkillCategoriesControllerFindAllQueryKey = () => {
  return [`/skill-categories`] as const;
};

export const getSkillCategoriesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<typeof customInstance>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getSkillCategoriesControllerFindAllQueryKey();

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>
  > = ({ signal }) => skillCategoriesControllerFindAll(requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type SkillCategoriesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>
>;
export type SkillCategoriesControllerFindAllQueryError = ErrorType<unknown>;

export function useSkillCategoriesControllerFindAll<
  TData = Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSkillCategoriesControllerFindAll<
  TData = Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useSkillCategoriesControllerFindAll<
  TData = Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 스킬 카테고리 전체 조회
 */

export function useSkillCategoriesControllerFindAll<
  TData = Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof skillCategoriesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getSkillCategoriesControllerFindAllQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary 스킬 카테고리 생성 (ADMIN)
 */
export const skillCategoriesControllerCreate = (
  createSkillCategoryDto: BodyType<CreateSkillCategoryDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SkillCategoriesControllerCreate200>(
    {
      url: `/skill-categories`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createSkillCategoryDto,
      signal,
    },
    options,
  );
};

export const getSkillCategoriesControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof skillCategoriesControllerCreate>>,
    TError,
    { data: BodyType<CreateSkillCategoryDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof skillCategoriesControllerCreate>>,
  TError,
  { data: BodyType<CreateSkillCategoryDto> },
  TContext
> => {
  const mutationKey = ["skillCategoriesControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof skillCategoriesControllerCreate>>,
    { data: BodyType<CreateSkillCategoryDto> }
  > = (props) => {
    const { data } = props ?? {};

    return skillCategoriesControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SkillCategoriesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof skillCategoriesControllerCreate>>
>;
export type SkillCategoriesControllerCreateMutationBody =
  BodyType<CreateSkillCategoryDto>;
export type SkillCategoriesControllerCreateMutationError = ErrorType<void>;

/**
 * @summary 스킬 카테고리 생성 (ADMIN)
 */
export const useSkillCategoriesControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof skillCategoriesControllerCreate>>,
      TError,
      { data: BodyType<CreateSkillCategoryDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof skillCategoriesControllerCreate>>,
  TError,
  { data: BodyType<CreateSkillCategoryDto> },
  TContext
> => {
  return useMutation(
    getSkillCategoriesControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary 스킬 카테고리 수정 (ADMIN)
 */
export const skillCategoriesControllerUpdate = (
  id: number,
  updateSkillCategoryDto: BodyType<UpdateSkillCategoryDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SkillCategoriesControllerUpdate200>(
    {
      url: `/skill-categories/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateSkillCategoryDto,
      signal,
    },
    options,
  );
};

export const getSkillCategoriesControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof skillCategoriesControllerUpdate>>,
    TError,
    { id: number; data: BodyType<UpdateSkillCategoryDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof skillCategoriesControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateSkillCategoryDto> },
  TContext
> => {
  const mutationKey = ["skillCategoriesControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof skillCategoriesControllerUpdate>>,
    { id: number; data: BodyType<UpdateSkillCategoryDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return skillCategoriesControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SkillCategoriesControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof skillCategoriesControllerUpdate>>
>;
export type SkillCategoriesControllerUpdateMutationBody =
  BodyType<UpdateSkillCategoryDto>;
export type SkillCategoriesControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary 스킬 카테고리 수정 (ADMIN)
 */
export const useSkillCategoriesControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof skillCategoriesControllerUpdate>>,
      TError,
      { id: number; data: BodyType<UpdateSkillCategoryDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof skillCategoriesControllerUpdate>>,
  TError,
  { id: number; data: BodyType<UpdateSkillCategoryDto> },
  TContext
> => {
  return useMutation(
    getSkillCategoriesControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * 해당 카테고리에 속한 스킬이 있으면 삭제할 수 없습니다. (409)
 * @summary 스킬 카테고리 삭제 (ADMIN)
 */
export const skillCategoriesControllerRemove = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<SkillCategoriesControllerRemove200>(
    { url: `/skill-categories/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getSkillCategoriesControllerRemoveMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof skillCategoriesControllerRemove>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof skillCategoriesControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["skillCategoriesControllerRemove"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof skillCategoriesControllerRemove>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return skillCategoriesControllerRemove(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SkillCategoriesControllerRemoveMutationResult = NonNullable<
  Awaited<ReturnType<typeof skillCategoriesControllerRemove>>
>;

export type SkillCategoriesControllerRemoveMutationError = ErrorType<void>;

/**
 * @summary 스킬 카테고리 삭제 (ADMIN)
 */
export const useSkillCategoriesControllerRemove = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof skillCategoriesControllerRemove>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof skillCategoriesControllerRemove>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getSkillCategoriesControllerRemoveMutationOptions(options),
    queryClient,
  );
};
