/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 1.4.2
 */
import { useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import { customInstance } from "../../http-client";
import type { ErrorType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const webpageControllerGetFile = (
  fileName: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<void>(
    { url: `/webpage/${fileName}`, method: "GET", signal },
    options,
  );
};

export const getWebpageControllerGetFileQueryKey = (fileName: string) => {
  return [`/webpage/${fileName}`] as const;
};

export const getWebpageControllerGetFileQueryOptions = <
  TData = Awaited<ReturnType<typeof webpageControllerGetFile>>,
  TError = ErrorType<unknown>,
>(
  fileName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof webpageControllerGetFile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getWebpageControllerGetFileQueryKey(fileName);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof webpageControllerGetFile>>
  > = ({ signal }) =>
    webpageControllerGetFile(fileName, requestOptions, signal);

  return {
    queryKey,
    queryFn,
    enabled: fileName !== null && fileName !== undefined,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<typeof webpageControllerGetFile>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type WebpageControllerGetFileQueryResult = NonNullable<
  Awaited<ReturnType<typeof webpageControllerGetFile>>
>;
export type WebpageControllerGetFileQueryError = ErrorType<unknown>;

export function useWebpageControllerGetFile<
  TData = Awaited<ReturnType<typeof webpageControllerGetFile>>,
  TError = ErrorType<unknown>,
>(
  fileName: string,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof webpageControllerGetFile>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof webpageControllerGetFile>>,
          TError,
          Awaited<ReturnType<typeof webpageControllerGetFile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWebpageControllerGetFile<
  TData = Awaited<ReturnType<typeof webpageControllerGetFile>>,
  TError = ErrorType<unknown>,
>(
  fileName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof webpageControllerGetFile>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof webpageControllerGetFile>>,
          TError,
          Awaited<ReturnType<typeof webpageControllerGetFile>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useWebpageControllerGetFile<
  TData = Awaited<ReturnType<typeof webpageControllerGetFile>>,
  TError = ErrorType<unknown>,
>(
  fileName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof webpageControllerGetFile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};

export function useWebpageControllerGetFile<
  TData = Awaited<ReturnType<typeof webpageControllerGetFile>>,
  TError = ErrorType<unknown>,
>(
  fileName: string,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof webpageControllerGetFile>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getWebpageControllerGetFileQueryOptions(
    fileName,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}
