/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.1.4
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CreateJobTypeDto,
  JobTypeControllerCreate200,
  JobTypeControllerDelete200,
  JobTypeControllerFindAll200,
  JobTypeControllerFindAllParams,
  JobTypeControllerUpdate200,
  UpdateJobTypeDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * jobType 은 createdAt 이 없어 sort 는 id·name 만 허용하며 기본값은 name 입니다.
 * @summary 모든 job type 을 조회합니다. (public)
 */
export const jobTypeControllerFindAll = (
  params: JobTypeControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<JobTypeControllerFindAll200>(
    { url: `/job-types`, method: "GET", params, signal },
    options,
  );
};

export const getJobTypeControllerFindAllQueryKey = (
  params?: JobTypeControllerFindAllParams,
) => {
  return [`/job-types`, ...(params ? [params] : [])] as const;
};

export const getJobTypeControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: JobTypeControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ?? getJobTypeControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof jobTypeControllerFindAll>>
  > = ({ signal }) => jobTypeControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type JobTypeControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof jobTypeControllerFindAll>>
>;
export type JobTypeControllerFindAllQueryError = ErrorType<unknown>;

export function useJobTypeControllerFindAll<
  TData = Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: JobTypeControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof jobTypeControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobTypeControllerFindAll<
  TData = Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: JobTypeControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof jobTypeControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useJobTypeControllerFindAll<
  TData = Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: JobTypeControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 모든 job type 을 조회합니다. (public)
 */

export function useJobTypeControllerFindAll<
  TData = Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: JobTypeControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof jobTypeControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getJobTypeControllerFindAllQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * @summary job type 생성 (ADMIN)
 */
export const jobTypeControllerCreate = (
  createJobTypeDto: BodyType<CreateJobTypeDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<JobTypeControllerCreate200>(
    {
      url: `/job-types`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createJobTypeDto,
      signal,
    },
    options,
  );
};

export const getJobTypeControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof jobTypeControllerCreate>>,
    TError,
    { data: BodyType<CreateJobTypeDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof jobTypeControllerCreate>>,
  TError,
  { data: BodyType<CreateJobTypeDto> },
  TContext
> => {
  const mutationKey = ["jobTypeControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof jobTypeControllerCreate>>,
    { data: BodyType<CreateJobTypeDto> }
  > = (props) => {
    const { data } = props ?? {};

    return jobTypeControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JobTypeControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof jobTypeControllerCreate>>
>;
export type JobTypeControllerCreateMutationBody = BodyType<CreateJobTypeDto>;
export type JobTypeControllerCreateMutationError = ErrorType<void>;

/**
 * @summary job type 생성 (ADMIN)
 */
export const useJobTypeControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof jobTypeControllerCreate>>,
      TError,
      { data: BodyType<CreateJobTypeDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof jobTypeControllerCreate>>,
  TError,
  { data: BodyType<CreateJobTypeDto> },
  TContext
> => {
  return useMutation(
    getJobTypeControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary job type 수정 (ADMIN)
 */
export const jobTypeControllerUpdate = (
  id: string,
  updateJobTypeDto: BodyType<UpdateJobTypeDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<JobTypeControllerUpdate200>(
    {
      url: `/job-types/${id}`,
      method: "PATCH",
      headers: { "Content-Type": "application/json" },
      data: updateJobTypeDto,
      signal,
    },
    options,
  );
};

export const getJobTypeControllerUpdateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof jobTypeControllerUpdate>>,
    TError,
    { id: string; data: BodyType<UpdateJobTypeDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof jobTypeControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateJobTypeDto> },
  TContext
> => {
  const mutationKey = ["jobTypeControllerUpdate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof jobTypeControllerUpdate>>,
    { id: string; data: BodyType<UpdateJobTypeDto> }
  > = (props) => {
    const { id, data } = props ?? {};

    return jobTypeControllerUpdate(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JobTypeControllerUpdateMutationResult = NonNullable<
  Awaited<ReturnType<typeof jobTypeControllerUpdate>>
>;
export type JobTypeControllerUpdateMutationBody = BodyType<UpdateJobTypeDto>;
export type JobTypeControllerUpdateMutationError = ErrorType<void>;

/**
 * @summary job type 수정 (ADMIN)
 */
export const useJobTypeControllerUpdate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof jobTypeControllerUpdate>>,
      TError,
      { id: string; data: BodyType<UpdateJobTypeDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof jobTypeControllerUpdate>>,
  TError,
  { id: string; data: BodyType<UpdateJobTypeDto> },
  TContext
> => {
  return useMutation(
    getJobTypeControllerUpdateMutationOptions(options),
    queryClient,
  );
};
/**
 * @summary job type 삭제 (ADMIN)
 */
export const jobTypeControllerDelete = (
  id: string,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<JobTypeControllerDelete200>(
    { url: `/job-types/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getJobTypeControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof jobTypeControllerDelete>>,
    TError,
    { id: string },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof jobTypeControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  const mutationKey = ["jobTypeControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof jobTypeControllerDelete>>,
    { id: string }
  > = (props) => {
    const { id } = props ?? {};

    return jobTypeControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type JobTypeControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof jobTypeControllerDelete>>
>;

export type JobTypeControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary job type 삭제 (ADMIN)
 */
export const useJobTypeControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof jobTypeControllerDelete>>,
      TError,
      { id: string },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof jobTypeControllerDelete>>,
  TError,
  { id: string },
  TContext
> => {
  return useMutation(
    getJobTypeControllerDeleteMutationOptions(options),
    queryClient,
  );
};
