/**
 * Generated by orval v8.20.0 🍺
 * Do not edit manually.
 * 프로필 카드 공유 서비스 API
 * 프로필 카드 공유 서비스 백엔드
 * OpenAPI spec version: 0.4.1
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from "@tanstack/react-query";

import type {
  CardBackgroundImagesControllerCreate200,
  CardBackgroundImagesControllerDelete200,
  CardBackgroundImagesControllerFindAll200,
  CardBackgroundImagesControllerFindAllParams,
  CreateCardBackgroundImageDto,
} from "../../model";

import { customInstance } from "../../http-client";
import type { ErrorType, BodyType } from "../../http-client";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(
  query: T,
  queryKey: K,
): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === "queryKey") continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

/**
 * 등록된 카드 배경 이미지를 페이지네이션으로 조회합니다.
 * 각 항목의 imageUrl 은 base URL 이며, 실제 이미지는 `${imageUrl}/282x400.webp` 처럼 접근합니다.
 *
 * **요청 query**
 * - page, limit, order: 페이지네이션 옵션
 * - sort: 정렬 컬럼 (id·createdAt, 기본 createdAt)
 * @summary 카드 배경 이미지 목록 조회
 */
export const cardBackgroundImagesControllerFindAll = (
  params: CardBackgroundImagesControllerFindAllParams,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CardBackgroundImagesControllerFindAll200>(
    { url: `/card-background-images`, method: "GET", params, signal },
    options,
  );
};

export const getCardBackgroundImagesControllerFindAllQueryKey = (
  params?: CardBackgroundImagesControllerFindAllParams,
) => {
  return [`/card-background-images`, ...(params ? [params] : [])] as const;
};

export const getCardBackgroundImagesControllerFindAllQueryOptions = <
  TData = Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CardBackgroundImagesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey =
    queryOptions?.queryKey ??
    getCardBackgroundImagesControllerFindAllQueryKey(params);

  const queryFn: QueryFunction<
    Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>
  > = ({ signal }) =>
    cardBackgroundImagesControllerFindAll(params, requestOptions, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type CardBackgroundImagesControllerFindAllQueryResult = NonNullable<
  Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>
>;
export type CardBackgroundImagesControllerFindAllQueryError =
  ErrorType<unknown>;

export function useCardBackgroundImagesControllerFindAll<
  TData = Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CardBackgroundImagesControllerFindAllParams,
  options: {
    query: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCardBackgroundImagesControllerFindAll<
  TData = Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CardBackgroundImagesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
        TError,
        TData
      >
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
          TError,
          Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>
        >,
        "initialData"
      >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
export function useCardBackgroundImagesControllerFindAll<
  TData = Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CardBackgroundImagesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
};
/**
 * @summary 카드 배경 이미지 목록 조회
 */

export function useCardBackgroundImagesControllerFindAll<
  TData = Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
  TError = ErrorType<unknown>,
>(
  params: CardBackgroundImagesControllerFindAllParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<typeof cardBackgroundImagesControllerFindAll>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & {
  queryKey: DataTag<QueryKey, TData, TError>;
} {
  const queryOptions = getCardBackgroundImagesControllerFindAllQueryOptions(
    params,
    options,
  );

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<
    TData,
    TError
  > & { queryKey: DataTag<QueryKey, TData, TError> };

  return withQueryKey(query, queryOptions.queryKey);
}

/**
 * 업로드 API(`POST /files/card-background-image/upload`)가 반환한 base URL 을
 * 카드 배경 선택지로 등록합니다.
 * @summary 카드 배경 이미지 등록 (ADMIN)
 */
export const cardBackgroundImagesControllerCreate = (
  createCardBackgroundImageDto: BodyType<CreateCardBackgroundImageDto>,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CardBackgroundImagesControllerCreate200>(
    {
      url: `/card-background-images`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createCardBackgroundImageDto,
      signal,
    },
    options,
  );
};

export const getCardBackgroundImagesControllerCreateMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cardBackgroundImagesControllerCreate>>,
    TError,
    { data: BodyType<CreateCardBackgroundImageDto> },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cardBackgroundImagesControllerCreate>>,
  TError,
  { data: BodyType<CreateCardBackgroundImageDto> },
  TContext
> => {
  const mutationKey = ["cardBackgroundImagesControllerCreate"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cardBackgroundImagesControllerCreate>>,
    { data: BodyType<CreateCardBackgroundImageDto> }
  > = (props) => {
    const { data } = props ?? {};

    return cardBackgroundImagesControllerCreate(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CardBackgroundImagesControllerCreateMutationResult = NonNullable<
  Awaited<ReturnType<typeof cardBackgroundImagesControllerCreate>>
>;
export type CardBackgroundImagesControllerCreateMutationBody =
  BodyType<CreateCardBackgroundImageDto>;
export type CardBackgroundImagesControllerCreateMutationError = ErrorType<void>;

/**
 * @summary 카드 배경 이미지 등록 (ADMIN)
 */
export const useCardBackgroundImagesControllerCreate = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cardBackgroundImagesControllerCreate>>,
      TError,
      { data: BodyType<CreateCardBackgroundImageDto> },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cardBackgroundImagesControllerCreate>>,
  TError,
  { data: BodyType<CreateCardBackgroundImageDto> },
  TContext
> => {
  return useMutation(
    getCardBackgroundImagesControllerCreateMutationOptions(options),
    queryClient,
  );
};
/**
 * 등록된 카드 배경 선택지를 삭제합니다. 존재하지 않으면 404 를 반환합니다.
 * (S3 원본 이미지 및 이미 이 URL 을 사용 중인 카드는 영향받지 않습니다.)
 * @summary 카드 배경 이미지 삭제 (ADMIN)
 */
export const cardBackgroundImagesControllerDelete = (
  id: number,
  options?: SecondParameter<typeof customInstance>,
  signal?: AbortSignal,
) => {
  return customInstance<CardBackgroundImagesControllerDelete200>(
    { url: `/card-background-images/${id}`, method: "DELETE", signal },
    options,
  );
};

export const getCardBackgroundImagesControllerDeleteMutationOptions = <
  TError = ErrorType<void>,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cardBackgroundImagesControllerDelete>>,
    TError,
    { id: number },
    TContext
  >;
  request?: SecondParameter<typeof customInstance>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cardBackgroundImagesControllerDelete>>,
  TError,
  { id: number },
  TContext
> => {
  const mutationKey = ["cardBackgroundImagesControllerDelete"];
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation &&
      "mutationKey" in options.mutation &&
      options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cardBackgroundImagesControllerDelete>>,
    { id: number }
  > = (props) => {
    const { id } = props ?? {};

    return cardBackgroundImagesControllerDelete(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CardBackgroundImagesControllerDeleteMutationResult = NonNullable<
  Awaited<ReturnType<typeof cardBackgroundImagesControllerDelete>>
>;

export type CardBackgroundImagesControllerDeleteMutationError = ErrorType<void>;

/**
 * @summary 카드 배경 이미지 삭제 (ADMIN)
 */
export const useCardBackgroundImagesControllerDelete = <
  TError = ErrorType<void>,
  TContext = unknown,
>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cardBackgroundImagesControllerDelete>>,
      TError,
      { id: number },
      TContext
    >;
    request?: SecondParameter<typeof customInstance>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cardBackgroundImagesControllerDelete>>,
  TError,
  { id: number },
  TContext
> => {
  return useMutation(
    getCardBackgroundImagesControllerDeleteMutationOptions(options),
    queryClient,
  );
};
